import type {
  ServerNode,
  ResourceMetric,
  SystemIncident,
  SystemHealthKpis,
} from './system-health.types';

export const INITIAL_SERVER_NODES: ServerNode[] = [
  {
    id: 'node-api-edge',
    name: 'API Edge Gateway Cluster',
    type: 'api_cluster',
    region: 'me-central-1 (Riyadh)',
    status: 'healthy',
    uptime: '99.99%',
    latencyMs: 28,
    cpuPercent: 32,
    memoryPercent: 48,
    detailsEn: 'Load balanced across 8 container instances handling HTTP/2 & gRPC ingress.',
    detailsAr: 'توزيع الأحمال عبر 8 خوادم حاويات لمعالجة استدعاءات HTTP/2 و gRPC.',
    activeInstances: 8,
    lastHealthCheck: 'Just now',
  },
  {
    id: 'node-postgres-primary',
    name: 'PostgreSQL Primary & Multi-AZ Replicas',
    type: 'database',
    region: 'me-central-1 (Riyadh / Jeddah)',
    status: 'healthy',
    uptime: '99.98%',
    latencyMs: 14,
    cpuPercent: 24,
    memoryPercent: 52,
    detailsEn: 'Primary DB with synchronous standby replica. Replication lag: 6ms.',
    detailsAr: 'قاعدة البيانات الرئيسية مع خادم متزامن للاسترداد. نسبة التأخير: 6 مللي ثانية.',
    activeInstances: 3,
    lastHealthCheck: '10s ago',
  },
  {
    id: 'node-redis-cache',
    name: 'Redis In-Memory Distributed Cluster',
    type: 'cache',
    region: 'me-central-1 (Riyadh)',
    status: 'healthy',
    uptime: '100.0%',
    latencyMs: 4,
    cpuPercent: 12,
    memoryPercent: 28,
    detailsEn: 'Session storage, rate limiting keys, and real-time Pub/Sub channels.',
    detailsAr: 'تخزين الجلسات، مفاتيح تحديد الاستهلاك، وقنوات النشر والاشتراك اللحظية.',
    activeInstances: 4,
    lastHealthCheck: '5s ago',
  },
  {
    id: 'node-bullmq-workers',
    name: 'BullMQ Async Job Fleet',
    type: 'workers',
    region: 'me-central-1 (Riyadh)',
    status: 'healthy',
    uptime: '99.95%',
    latencyMs: 36,
    cpuPercent: 41,
    memoryPercent: 63,
    detailsEn: 'Dispatches ZATCA XML stamping, invoice PDF rendering, and bulk notifications.',
    detailsAr: 'معالجة فواتير الزكاة الرقمية، إنشاء ملفات PDF، وإرسال الإشعارات المجمعة.',
    activeInstances: 6,
    lastHealthCheck: '15s ago',
  },
  {
    id: 'node-pos-websockets',
    name: 'POS Terminal WebSocket Gateway',
    type: 'websockets',
    region: 'me-central-1 (Riyadh)',
    status: 'healthy',
    uptime: '99.99%',
    latencyMs: 12,
    cpuPercent: 19,
    memoryPercent: 34,
    detailsEn: '640 active cashier screens connected with continuous keep-alive heartbeats.',
    detailsAr: '640 شاشة كاشير ونقطة بيع متصلة بنبض اتصال مستمر وتزامن فوري.',
    activeInstances: 4,
    lastHealthCheck: 'Just now',
  },
  {
    id: 'node-s3-gateway',
    name: 'Cloud Storage & CDN Edge',
    type: 'storage_gateway',
    region: 'Global CloudFront (Riyadh Edge)',
    status: 'healthy',
    uptime: '100.0%',
    latencyMs: 22,
    cpuPercent: 8,
    memoryPercent: 15,
    detailsEn: 'Accelerated content delivery for dish images, menu QR assets, and tax receipt archives.',
    detailsAr: 'تسريع تسليم صور المنيو وأصول باركود QR وأرشيف الفواتير الضريبية.',
    activeInstances: 12,
    lastHealthCheck: '30s ago',
  },
];

export const INITIAL_RESOURCE_METRICS: ResourceMetric[] = [
  {
    id: 'res-cpu',
    labelEn: 'Cluster CPU Utilization',
    labelAr: 'استهلاك المعالجات (CPU)',
    currentPercent: 28,
    displayValue: '28.4% Avg Load',
    status: 'normal',
    subTextEn: 'Load Average: 0.82 / 1.14 / 0.95',
    subTextAr: 'معدل الحمل: 0.82 / 1.14 / 0.95',
  },
  {
    id: 'res-ram',
    labelEn: 'Allocated System Memory (RAM)',
    labelAr: 'الذاكرة العشوائية (RAM)',
    currentPercent: 44,
    displayValue: '14.2 GB / 32.0 GB',
    status: 'normal',
    subTextEn: '17.8 GB Headroom Available',
    subTextAr: '17.8 جيجابايت مساحة شاغرة متاحة',
  },
  {
    id: 'res-disk',
    labelEn: 'Database NVMe Storage I/O',
    labelAr: 'سرعة القراءة والكتابة (IOPS)',
    currentPercent: 22,
    displayValue: '1,250 IOPS',
    status: 'normal',
    subTextEn: 'Read: 0.4ms | Write: 0.8ms Latency',
    subTextAr: 'قراءة: 0.4ms | كتابة: 0.8ms استجابة',
  },
  {
    id: 'res-network',
    labelEn: 'Network Bandwidth Ingress/Egress',
    labelAr: 'تدفق بيانات الشبكة (Bandwidth)',
    currentPercent: 35,
    displayValue: '245.8 Mbps',
    status: 'normal',
    subTextEn: 'Peak capacity: 1.0 Gbps Burst',
    subTextAr: 'السعة القصوى المتاحة: 1.0 Gbps',
  },
];

export const INITIAL_INCIDENTS: SystemIncident[] = [
  {
    id: 'inc-001',
    titleEn: 'Scheduled Database Autovacuum Completed',
    titleAr: 'اكتمال عملية الصيانة الدورية لقاعدة البيانات (Autovacuum)',
    severity: 'resolved',
    timestamp: '3 hours ago',
    descriptionEn: 'Routine table vacuuming and index rebalancing completed without locking transactions.',
    descriptionAr: 'تم الانتهاء من تحسين فهارس الجداول وتنظيف المساحات الشاغرة دون توقف المعاملات.',
  },
  {
    id: 'inc-002',
    titleEn: 'Worker Fleet Scaled to 6 Nodes',
    titleAr: 'توسعة تلقائية لأسطول عمال المهام إلى 6 خوادم',
    severity: 'info',
    timestamp: '6 hours ago',
    descriptionEn: 'Auto-scaled worker containers to handle high evening POS dinner rush traffic.',
    descriptionAr: 'تمت زيادة عقد خوادم المهام تلقائياً لمواكبة ذروة طلبات العشاء في المطاعم.',
  },
  {
    id: 'inc-003',
    titleEn: 'Wildcard SSL Certificate Renewed',
    titleAr: 'تجديد شهادة الأمان السحابية SSL لكافة النطاقات',
    severity: 'resolved',
    timestamp: '1 day ago',
    descriptionEn: 'Automated Let’s Encrypt renewal verified across *.mot7km.com with zero downtime.',
    descriptionAr: 'تم تجديد شهادة التشفير الآلي لكافة النطاقات الفرعية بنجاح دون أي توقف.',
  },
];

export const INITIAL_SYSTEM_KPIS: SystemHealthKpis = {
  uptimePercent: 99.98,
  avgLatencyMs: 32,
  activeDbConnections: 48,
  maxDbConnections: 200,
  jobQueueThroughput: 1420,
  failedJobsCount: 0,
};
