import type { Business } from './businesses.types';

export const mockBusinesses: Business[] = [
  {
    id: 't-101',
    name: 'Gourmet Cloud Kitchens',
    legalName: 'Gourmet Cloud Food Services LLC',
    subdomain: 'gourmet-cloud',
    customDomain: 'orders.gourmetcloud.sa',
    category: 'Cloud Kitchens',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Riyadh',
    crNumber: '1010892341',
    vatNumber: '310928374600003',
    currency: 'SAR',
    status: 'active',
    plan: 'Enterprise',
    billingCycle: 'annual',
    nextBillingDate: '2026-03-15',
    mrr: 1200,
    gmvTotal: 485000,
    ordersCount: 38400,
    branchesCount: 14,
    branchesLimit: 25,
    employeesCount: 68,
    employeesLimit: 120,
    storageUsedGb: 32.4,
    storageLimitGb: 100,
    apiCallsMonth: 245000,
    apiCallsLimit: 500000,
    owner: {
      name: 'Fahad Al-Otaibi',
      email: 'f.otaibi@gourmetcloud.sa',
      phone: '+966 50 123 4567',
      role: 'Chief Executive Officer',
    },
    branches: [
      { id: 'b-1', name: 'Al-Olaya Central Kitchen', city: 'Riyadh', isMain: true, status: 'active', staffCount: 14, ordersCount: 9400, revenueMonth: 124000 },
      { id: 'b-2', name: 'Al-Nakheel Express', city: 'Riyadh', isMain: false, status: 'active', staffCount: 8, ordersCount: 6200, revenueMonth: 82000 },
      { id: 'b-3', name: 'Al-Malqa Dark Kitchen', city: 'Riyadh', isMain: false, status: 'active', staffCount: 10, ordersCount: 7800, revenueMonth: 98000 },
      { id: 'b-4', name: 'Jeddah Corniche Hub', city: 'Jeddah', isMain: false, status: 'active', staffCount: 12, ordersCount: 8100, revenueMonth: 105000 },
    ],
    auditLogs: [
      { id: 'log-1', action: 'API Key Provisioned', actor: 'Root Super Admin', timestamp: '2026-09-24 14:20:00', details: 'High-throughput webhook API v2 endpoint activated', type: 'security' },
      { id: 'log-2', action: 'Plan Upgrade Confirmed', actor: 'System Billing Engine', timestamp: '2026-09-01 00:00:00', details: 'Upgraded to Enterprise Annual Plan with dedicated worker cluster', type: 'billing' },
      { id: 'log-3', action: 'Branch Added', actor: 'Fahad Al-Otaibi', timestamp: '2026-08-18 11:32:00', details: 'New kitchen facility provisioned in Jeddah', type: 'info' },
    ],
    createdAt: '2024-02-10',
    lastActiveAt: '2026-09-25 04:52:00',
    notes: 'Key enterprise tenant in KSA cloud kitchen vertical. Priority 24/7 SLA tier.',
  },
  {
    id: 't-102',
    name: 'Sultan Coffee Roasters',
    legalName: 'Sultan Specialty Coffee Group SAE',
    subdomain: 'sultan-coffee',
    customDomain: 'app.sultancoffee.com',
    category: 'Specialty Coffee & Bakery',
    country: 'Egypt',
    countryCode: 'EG',
    city: 'Cairo',
    crNumber: '4829103',
    vatNumber: 'EG-298371892',
    currency: 'EGP',
    status: 'active',
    plan: 'Enterprise',
    billingCycle: 'monthly',
    nextBillingDate: '2026-10-10',
    mrr: 950,
    gmvTotal: 342000,
    ordersCount: 42100,
    branchesCount: 12,
    branchesLimit: 15,
    employeesCount: 54,
    employeesLimit: 80,
    storageUsedGb: 28.1,
    storageLimitGb: 80,
    apiCallsMonth: 189000,
    apiCallsLimit: 300000,
    owner: {
      name: 'Tarek El-Sultan',
      email: 'tarek@sultancoffee.com',
      phone: '+20 100 234 5678',
      role: 'Founder & Managing Director',
    },
    branches: [
      { id: 'b-201', name: 'Zamalek Flagship', city: 'Cairo', isMain: true, status: 'active', staffCount: 12, ordersCount: 11200, revenueMonth: 94000 },
      { id: 'b-202', name: 'New Cairo Fifth Settlement', city: 'Cairo', isMain: false, status: 'active', staffCount: 10, ordersCount: 9800, revenueMonth: 82000 },
      { id: 'b-203', name: 'Maadi Degla Roastery', city: 'Cairo', isMain: false, status: 'active', staffCount: 8, ordersCount: 8400, revenueMonth: 71000 },
    ],
    auditLogs: [
      { id: 'log-201', action: 'Subscription Auto-Renewed', actor: 'Stripe Gateway', timestamp: '2026-09-10 02:00:00', details: 'Monthly recurring payment of $950 processed', type: 'billing' },
      { id: 'log-202', action: 'Employee Batch Onboarded', actor: 'Tarek El-Sultan', timestamp: '2026-09-04 15:10:00', details: 'Added 6 new baristas with POS operator permissions', type: 'info' },
    ],
    createdAt: '2024-05-18',
    lastActiveAt: '2026-09-25 04:35:00',
    notes: 'Premium coffee chain with rapid physical expansion across Greater Cairo.',
  },
  {
    id: 't-103',
    name: 'Urban Slice Pizza Hub',
    legalName: 'Urban Slice Artisanal Foods FZ-LLC',
    subdomain: 'urban-slice',
    customDomain: 'order.urbanslice.ae',
    category: 'Fast Casual Dining',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Dubai',
    crNumber: 'DUB-89218',
    vatNumber: '100293847500003',
    currency: 'AED',
    status: 'active',
    plan: 'Pro',
    billingCycle: 'monthly',
    nextBillingDate: '2026-10-02',
    mrr: 450,
    gmvTotal: 189000,
    ordersCount: 14800,
    branchesCount: 4,
    branchesLimit: 5,
    employeesCount: 22,
    employeesLimit: 30,
    storageUsedGb: 14.5,
    storageLimitGb: 30,
    apiCallsMonth: 78000,
    apiCallsLimit: 150000,
    owner: {
      name: 'Karim Mansour',
      email: 'karim@urbanslice.ae',
      phone: '+971 52 876 5432',
      role: 'Operations Lead',
    },
    branches: [
      { id: 'b-301', name: 'Dubai Marina Walk', city: 'Dubai', isMain: true, status: 'active', staffCount: 8, ordersCount: 6400, revenueMonth: 78000 },
      { id: 'b-302', name: 'Downtown Boulevard', city: 'Dubai', isMain: false, status: 'active', staffCount: 7, ordersCount: 4900, revenueMonth: 62000 },
      { id: 'b-303', name: 'JLT Cluster D', city: 'Dubai', isMain: false, status: 'active', staffCount: 7, ordersCount: 3500, revenueMonth: 49000 },
    ],
    auditLogs: [
      { id: 'log-301', action: 'QR Menu Theme Customized', actor: 'Karim Mansour', timestamp: '2026-09-22 18:40:00', details: 'Updated storefront palette to neon-amber', type: 'info' },
    ],
    createdAt: '2024-09-01',
    lastActiveAt: '2026-09-25 03:20:00',
  },
  {
    id: 't-104',
    name: 'Al-Ahram Hospitality Group',
    legalName: 'Al-Ahram Catering & Hotels Consortium',
    subdomain: 'ahram-hospitality',
    category: 'Restaurant Chain & Catering',
    country: 'Egypt',
    countryCode: 'EG',
    city: 'Alexandria',
    crNumber: 'ALX-19284',
    vatNumber: 'EG-908129481',
    currency: 'EGP',
    status: 'trial',
    plan: 'Enterprise',
    billingCycle: 'annual',
    nextBillingDate: '2026-10-08',
    mrr: 1400,
    gmvTotal: 95000,
    ordersCount: 8200,
    branchesCount: 6,
    branchesLimit: 20,
    employeesCount: 38,
    employeesLimit: 100,
    storageUsedGb: 19.8,
    storageLimitGb: 100,
    apiCallsMonth: 54000,
    apiCallsLimit: 500000,
    owner: {
      name: 'Nader Roushdy',
      email: 'n.roushdy@ahramgroup.eg',
      phone: '+20 122 345 6789',
      role: 'VP of Technology & ERP',
    },
    branches: [
      { id: 'b-401', name: 'Gleem Bay Waterfront', city: 'Alexandria', isMain: true, status: 'active', staffCount: 14, ordersCount: 3800, revenueMonth: 45000 },
      { id: 'b-402', name: 'Smouha City Centre', city: 'Alexandria', isMain: false, status: 'active', staffCount: 12, ordersCount: 2600, revenueMonth: 31000 },
    ],
    auditLogs: [
      { id: 'log-401', action: 'Enterprise Trial Activated', actor: 'Sales Engineering Lead', timestamp: '2026-09-18 10:00:00', details: '14-day full POC provisioned with multi-currency setup', type: 'info' },
    ],
    createdAt: '2026-09-18',
    lastActiveAt: '2026-09-25 01:15:00',
    notes: 'Trial conversion meeting scheduled with CFO on Oct 2nd.',
  },
  {
    id: 't-105',
    name: 'Taco Libre Street Kitchen',
    legalName: 'Taco Libre Fast Food Establishment',
    subdomain: 'taco-libre',
    category: 'Boutique Fast Food',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Jeddah',
    crNumber: '4030192847',
    vatNumber: '302918274600003',
    currency: 'SAR',
    status: 'active',
    plan: 'Starter',
    billingCycle: 'monthly',
    nextBillingDate: '2026-10-14',
    mrr: 150,
    gmvTotal: 42000,
    ordersCount: 3100,
    branchesCount: 1,
    branchesLimit: 2,
    employeesCount: 6,
    employeesLimit: 10,
    storageUsedGb: 4.8,
    storageLimitGb: 10,
    apiCallsMonth: 12000,
    apiCallsLimit: 50000,
    owner: {
      name: 'Rami Qabbani',
      email: 'rami@tacolibre.sa',
      phone: '+966 54 987 6543',
      role: 'Owner & Head Chef',
    },
    branches: [
      { id: 'b-501', name: 'Al-Rawdah Branch', city: 'Jeddah', isMain: true, status: 'active', staffCount: 6, ordersCount: 3100, revenueMonth: 42000 },
    ],
    auditLogs: [
      { id: 'log-501', action: 'Menu Item Synced', actor: 'Rami Qabbani', timestamp: '2026-09-23 20:10:00', details: 'Added 4 new taco combo items with QR price updates', type: 'info' },
    ],
    createdAt: '2025-01-12',
    lastActiveAt: '2026-09-24 23:10:00',
  },
  {
    id: 't-106',
    name: 'Riyadh Artisan Bakery',
    legalName: 'Artisan Baking Co. Ltd.',
    subdomain: 'artisan-bakery',
    category: 'Bakery & Confectionery',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Riyadh',
    crNumber: '1010394821',
    vatNumber: '310293847500003',
    currency: 'SAR',
    status: 'active',
    plan: 'Pro',
    billingCycle: 'annual',
    nextBillingDate: '2026-07-20',
    mrr: 380,
    gmvTotal: 165000,
    ordersCount: 12400,
    branchesCount: 3,
    branchesLimit: 5,
    employeesCount: 18,
    employeesLimit: 25,
    storageUsedGb: 11.2,
    storageLimitGb: 30,
    apiCallsMonth: 65000,
    apiCallsLimit: 150000,
    owner: {
      name: 'Nouf Al-Sudairi',
      email: 'nouf@artisanbakery.sa',
      phone: '+966 56 456 7890',
      role: 'Managing Partner',
    },
    branches: [
      { id: 'b-601', name: 'Al-Takhassusi Flagship', city: 'Riyadh', isMain: true, status: 'active', staffCount: 8, ordersCount: 5400, revenueMonth: 68000 },
      { id: 'b-602', name: 'Hittin Boulevard', city: 'Riyadh', isMain: false, status: 'active', staffCount: 6, ordersCount: 4200, revenueMonth: 55000 },
    ],
    auditLogs: [
      { id: 'log-601', action: 'Inventory Auto-Reorder Triggered', actor: 'Automated Agent', timestamp: '2026-09-24 08:00:00', details: 'French flour bulk purchase PO generated', type: 'info' },
    ],
    createdAt: '2024-07-20',
    lastActiveAt: '2026-09-25 04:10:00',
  },
  {
    id: 't-107',
    name: 'Desert Flame Grills',
    legalName: 'Desert Flame Hospitality Group',
    subdomain: 'desert-flame',
    category: 'Steakhouse & BBQ',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Dammam',
    crNumber: '2050192847',
    vatNumber: '300192837400003',
    currency: 'SAR',
    status: 'suspended',
    plan: 'Enterprise',
    billingCycle: 'monthly',
    nextBillingDate: '2026-09-12',
    mrr: 1100,
    gmvTotal: 280000,
    ordersCount: 19500,
    branchesCount: 8,
    branchesLimit: 15,
    employeesCount: 42,
    employeesLimit: 60,
    storageUsedGb: 29.8,
    storageLimitGb: 80,
    apiCallsMonth: 34000,
    apiCallsLimit: 300000,
    owner: {
      name: 'Saad Al-Dossari',
      email: 'saad@desertflame.sa',
      phone: '+966 55 321 0987',
      role: 'Owner & General Manager',
    },
    branches: [
      { id: 'b-701', name: 'Al-Khobar Corniche', city: 'Dammam', isMain: true, status: 'maintenance', staffCount: 12, ordersCount: 6200, revenueMonth: 78000 },
    ],
    auditLogs: [
      { id: 'log-701', action: 'Tenant Automatically Suspended', actor: 'Billing Sentinel', timestamp: '2026-09-18 04:00:00', details: 'Account suspended following 3 consecutive failed charge attempts and grace period expiration', type: 'billing' },
      { id: 'log-702', action: 'Dunning Email Sent', actor: 'Billing Sentinel', timestamp: '2026-09-15 09:00:00', details: 'Final notice delivered to owner email address', type: 'warning' },
    ],
    createdAt: '2024-03-14',
    lastActiveAt: '2026-09-18 03:45:00',
    suspendedReason: 'Repeated billing payment decline ($1,100). Grace period expired on Sept 18.',
  },
  {
    id: 't-108',
    name: 'Alexandria Seafood Co.',
    legalName: 'Mediterranean Seafood Group SAE',
    subdomain: 'alex-seafood',
    category: 'Seafood Fine Dining',
    country: 'Egypt',
    countryCode: 'EG',
    city: 'Alexandria',
    crNumber: 'ALX-98214',
    vatNumber: 'EG-391827461',
    currency: 'EGP',
    status: 'disabled',
    plan: 'Pro',
    billingCycle: 'monthly',
    nextBillingDate: '2026-11-01',
    mrr: 450,
    gmvTotal: 120000,
    ordersCount: 8900,
    branchesCount: 3,
    branchesLimit: 5,
    employeesCount: 16,
    employeesLimit: 25,
    storageUsedGb: 8.9,
    storageLimitGb: 30,
    apiCallsMonth: 5000,
    apiCallsLimit: 150000,
    owner: {
      name: 'Mahmoud Mansy',
      email: 'm.mansy@alexseafood.eg',
      phone: '+20 111 876 5432',
      role: 'General Manager',
    },
    branches: [
      { id: 'b-801', name: 'Bahary Ancient Harbour', city: 'Alexandria', isMain: true, status: 'closed', staffCount: 8, ordersCount: 4500, revenueMonth: 61000 },
    ],
    auditLogs: [
      { id: 'log-801', action: 'Tenant Voluntarily Frozen', actor: 'Root Super Admin', timestamp: '2026-09-01 12:00:00', details: 'Temporary administrative freeze requested by owner during seasonal renovation', type: 'info' },
    ],
    createdAt: '2024-11-05',
    lastActiveAt: '2026-09-01 11:50:00',
    notes: 'Voluntary temporary freeze due to physical branch remodelling. Auto-reactivation scheduled for Nov 1st.',
  },
];
