import type { GlobalUser } from './users.types';

export const INITIAL_GLOBAL_USERS: GlobalUser[] = [
  // 1. Super Admins
  {
    id: 'usr_root_1',
    name: 'Alex Morgan',
    email: 'superadmin@mot7km.com',
    phone: '+1 415 890 1200',
    role: 'super_admin',
    businessId: 'system',
    businessName: 'Mot7km Sovereign Root',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-25T05:32:00Z',
    createdAt: '2024-01-01',
    notes: 'Primary sovereign super-admin keyholder with full root capabilities',
    sessions: [
      {
        id: 'sess_101',
        deviceType: 'desktop',
        deviceModel: 'MacBook Pro M3 Max',
        browser: 'Chrome 124.0 on macOS Sonoma',
        ipAddress: '156.204.18.92',
        location: 'Riyadh, SA',
        lastActive: 'Just now',
        isCurrent: true,
      },
      {
        id: 'sess_102',
        deviceType: 'mobile',
        deviceModel: 'iPhone 16 Pro Max',
        browser: 'Safari Mobile 18.1',
        ipAddress: '178.80.12.44',
        location: 'Riyadh, SA',
        lastActive: '25 mins ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_root_2',
    name: 'Ziyad Al-Farhan',
    email: 'z.farhan@mot7km.com',
    phone: '+966 50 123 9988',
    role: 'super_admin',
    businessId: 'system',
    businessName: 'Mot7km Sovereign Root',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-24T18:40:00Z',
    createdAt: '2024-03-15',
    notes: 'Chief Information Security Officer & Root Auditor',
    sessions: [
      {
        id: 'sess_103',
        deviceType: 'desktop',
        deviceModel: 'ThinkPad X1 Carbon',
        browser: 'Firefox Developer Edition on Linux',
        ipAddress: '188.161.45.10',
        location: 'Jeddah, SA',
        lastActive: '11 hours ago',
        isCurrent: false,
      },
    ],
  },

  // 2. Global Support Staff
  {
    id: 'usr_sup_1',
    name: 'Maya Chen',
    email: 'maya.chen@mot7km.support',
    phone: '+971 4 330 8920',
    role: 'support_staff',
    businessId: 'system',
    businessName: 'Mot7km Global Support Tier-3',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-25T04:15:00Z',
    createdAt: '2024-06-10',
    sessions: [
      {
        id: 'sess_104',
        deviceType: 'desktop',
        deviceModel: 'Dell Precision 5570',
        browser: 'Chrome 123.0 on Windows 11',
        ipAddress: '194.170.82.14',
        location: 'Dubai, AE',
        lastActive: '1 hour ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_sup_2',
    name: 'Omar Al-Husseini',
    email: 'omar.h@mot7km.support',
    phone: '+20 2 2795 4410',
    role: 'support_staff',
    businessId: 'system',
    businessName: 'Mot7km Global Support Tier-3',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-24T22:10:00Z',
    createdAt: '2024-08-01',
    sessions: [
      {
        id: 'sess_105',
        deviceType: 'desktop',
        deviceModel: 'iMac 24-inch M3',
        browser: 'Safari 17.4 on macOS',
        ipAddress: '197.34.120.55',
        location: 'Cairo, EG',
        lastActive: '7 hours ago',
        isCurrent: false,
      },
    ],
  },

  // 3. Business Owners
  {
    id: 'usr_own_1',
    name: 'Fahad Al-Otaibi',
    email: 'f_otaibi@gourmetcloud.sa',
    phone: '+966 50 123 4567',
    role: 'business_owner',
    businessId: 't-101',
    businessName: 'Gourmet Cloud Kitchens',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-25T03:40:00Z',
    createdAt: '2025-01-15',
    sessions: [
      {
        id: 'sess_106',
        deviceType: 'desktop',
        deviceModel: 'MacBook Air M2',
        browser: 'Chrome 122.0 on macOS',
        ipAddress: '212.118.140.22',
        location: 'Riyadh, SA',
        lastActive: '2 hours ago',
        isCurrent: false,
      },
      {
        id: 'sess_107',
        deviceType: 'mobile',
        deviceModel: 'Samsung Galaxy S24 Ultra',
        browser: 'Samsung Internet 24.0',
        ipAddress: '178.80.99.12',
        location: 'Riyadh, SA',
        lastActive: '15 mins ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_own_2',
    name: 'Dr. Tariq Al-Ghamdi',
    email: 'tariq@apexlogistics.sa',
    phone: '+966 55 987 6543',
    role: 'business_owner',
    businessId: 't-102',
    businessName: 'Apex Logistics & Warehousing',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-24T14:20:00Z',
    createdAt: '2025-04-10',
    sessions: [
      {
        id: 'sess_108',
        deviceType: 'desktop',
        deviceModel: 'HP EliteBook 840 G9',
        browser: 'Edge 123.0 on Windows 11',
        ipAddress: '188.161.90.5',
        location: 'Jeddah, SA',
        lastActive: '15 hours ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_own_3',
    name: 'Sara Al-Mansoor',
    email: 'sara@luxeperfumes.ae',
    phone: '+971 50 445 8899',
    role: 'business_owner',
    businessId: 't-103',
    businessName: 'Luxe Perfumes & Cosmetics',
    status: 'locked',
    mfaEnabled: true,
    lastLogin: '2026-09-22T09:12:00Z',
    createdAt: '2025-06-01',
    notes: 'Temporarily locked after 5 consecutive failed MFA token attempts from unexpected IP',
    sessions: [],
  },
  {
    id: 'usr_own_4',
    name: 'Nader Roushdy',
    email: 'n.roushdy@ahramgroup.eg',
    phone: '+20 122 345 6789',
    role: 'business_owner',
    businessId: 't-104',
    businessName: 'Al-Ahram Hospitality Group',
    status: 'active',
    mfaEnabled: false,
    lastLogin: '2026-09-25T01:10:00Z',
    createdAt: '2026-09-18',
    sessions: [
      {
        id: 'sess_109',
        deviceType: 'desktop',
        deviceModel: 'Mac mini M2',
        browser: 'Chrome 122.0 on macOS',
        ipAddress: '197.45.18.2',
        location: 'Cairo, EG',
        lastActive: '4 hours ago',
        isCurrent: false,
      },
    ],
  },

  // 4. Branch Managers
  {
    id: 'usr_mgr_1',
    name: 'Rayan Mansour',
    email: 'r.mansour@gourmetcloud.sa',
    phone: '+966 54 888 2341',
    role: 'branch_manager',
    businessId: 't-101',
    businessName: 'Gourmet Cloud Kitchens',
    branchId: 'br_olaya',
    branchName: 'Olaya Central Hub',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-25T05:00:00Z',
    createdAt: '2025-02-01',
    sessions: [
      {
        id: 'sess_110',
        deviceType: 'tablet',
        deviceModel: 'iPad Pro 11-inch M4',
        browser: 'Safari on iPadOS',
        ipAddress: '212.118.140.28',
        location: 'Riyadh, SA',
        lastActive: '30 mins ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_mgr_2',
    name: 'Hisham Fikry',
    email: 'hisham.f@ahramgroup.eg',
    phone: '+20 100 882 1199',
    role: 'branch_manager',
    businessId: 't-104',
    businessName: 'Al-Ahram Hospitality Group',
    branchId: 'br_zamalek',
    branchName: 'Zamalek Grand Restaurant',
    status: 'active',
    mfaEnabled: true,
    lastLogin: '2026-09-25T02:40:00Z',
    createdAt: '2026-09-20',
    sessions: [
      {
        id: 'sess_111',
        deviceType: 'desktop',
        deviceModel: 'Lenovo ThinkCentre Neo',
        browser: 'Chrome 122 on Windows 10',
        ipAddress: '197.45.18.90',
        location: 'Cairo, EG',
        lastActive: '3 hours ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_mgr_3',
    name: 'Layla Qasim',
    email: 'layla@luxeperfumes.ae',
    phone: '+971 55 120 7744',
    role: 'branch_manager',
    businessId: 't-103',
    businessName: 'Luxe Perfumes & Cosmetics',
    branchId: 'br_dubai_mall',
    branchName: 'Dubai Mall Flagship Store',
    status: 'disabled',
    mfaEnabled: true,
    lastLogin: '2026-09-10T12:00:00Z',
    createdAt: '2025-07-15',
    notes: 'Voluntarily disabled pending employee leave of absence',
    sessions: [],
  },

  // 5. Cashiers & POS Operators
  {
    id: 'usr_csh_1',
    name: 'Mona Adel',
    email: 'mona.pos@gourmetcloud.sa',
    phone: '+966 56 331 4455',
    role: 'cashier',
    businessId: 't-101',
    businessName: 'Gourmet Cloud Kitchens',
    branchId: 'br_olaya',
    branchName: 'Olaya Central Hub',
    status: 'active',
    mfaEnabled: false,
    lastLogin: '2026-09-25T05:28:00Z',
    createdAt: '2025-03-01',
    sessions: [
      {
        id: 'sess_112',
        deviceType: 'pos_terminal',
        deviceModel: 'Sunmi T2s Dual Touch POS',
        browser: 'Mot7km Cloud POS App v2.4',
        ipAddress: '10.20.1.45',
        location: 'Olaya Counter #1, Riyadh',
        lastActive: '5 mins ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_csh_2',
    name: 'Ahmed Saeed',
    email: 'ahmed.csh@ahramgroup.eg',
    phone: '+20 111 773 2210',
    role: 'cashier',
    businessId: 't-104',
    businessName: 'Al-Ahram Hospitality Group',
    branchId: 'br_zamalek',
    branchName: 'Zamalek Grand Restaurant',
    status: 'active',
    mfaEnabled: false,
    lastLogin: '2026-09-25T05:12:00Z',
    createdAt: '2026-09-21',
    sessions: [
      {
        id: 'sess_113',
        deviceType: 'pos_terminal',
        deviceModel: 'Elo Touch I-Series POS',
        browser: 'Mot7km Cloud POS App v2.4',
        ipAddress: '192.168.10.12',
        location: 'Zamalek Register #2, Cairo',
        lastActive: '20 mins ago',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'usr_csh_3',
    name: 'Bilal Khan',
    email: 'bilal@apexlogistics.sa',
    phone: '+966 53 440 9911',
    role: 'cashier',
    businessId: 't-102',
    businessName: 'Apex Logistics & Warehousing',
    branchId: 'br_warehouse_1',
    branchName: 'Jeddah Central Port Hub',
    status: 'pending',
    mfaEnabled: false,
    lastLogin: 'Never',
    createdAt: '2026-09-24',
    notes: 'Invitation sent; awaiting initial password setup',
    sessions: [],
  },
];
