import type { PlatformStorageOverview, BusinessStorageRecord } from './storage.types';

export const INITIAL_STORAGE_OVERVIEW: PlatformStorageOverview = {
  totalCapacityGB: 500,
  usedCapacityGB: 214.6,
  availableCapacityGB: 285.4,
  usagePercentage: 42.9,
  monthlyGrowthGB: 24.8,
  criticalTenantsCount: 2,
  breakdown: {
    imagesGB: 118.4,
    imagesPercent: 55.2,
    documentsGB: 42.1,
    documentsPercent: 19.6,
    backupsGB: 38.2,
    backupsPercent: 17.8,
    logsGB: 15.9,
    logsPercent: 7.4,
  },
};

export const INITIAL_BUSINESS_STORAGES: BusinessStorageRecord[] = [
  {
    businessId: 'biz_101',
    businessName: 'Al-Sultan Gourmet Grill',
    businessCode: 'BUS-101',
    planName: 'Pro Business',
    usedGB: 4.2,
    quotaGB: 10,
    usagePercent: 42,
    status: 'normal',
    fileCount: 1420,
    categoryBreakdown: {
      imagesGB: 2.8,
      documentsGB: 0.8,
      backupsGB: 0.4,
      logsGB: 0.2,
    },
    lastUploadAt: '10 mins ago',
  },
  {
    businessId: 'biz_102',
    businessName: 'Café Nero Artisan',
    businessCode: 'BUS-102',
    planName: 'Basic Starter',
    usedGB: 1.1,
    quotaGB: 5,
    usagePercent: 22,
    status: 'normal',
    fileCount: 480,
    categoryBreakdown: {
      imagesGB: 0.7,
      documentsGB: 0.2,
      backupsGB: 0.1,
      logsGB: 0.1,
    },
    lastUploadAt: '1 hour ago',
  },
  {
    businessId: 'biz_105',
    businessName: 'Golden Fork Hospitality',
    businessCode: 'BUS-105',
    planName: 'Pro Business',
    usedGB: 8.9,
    quotaGB: 10,
    usagePercent: 89,
    status: 'warning',
    fileCount: 3890,
    categoryBreakdown: {
      imagesGB: 5.4,
      documentsGB: 1.8,
      backupsGB: 1.2,
      logsGB: 0.5,
    },
    lastUploadAt: '5 mins ago',
  },
  {
    businessId: 'biz_103',
    businessName: 'Marina Fresh Roastery',
    businessCode: 'BUS-103',
    planName: 'Pro Business',
    usedGB: 9.4,
    quotaGB: 10,
    usagePercent: 94,
    status: 'critical',
    fileCount: 4120,
    categoryBreakdown: {
      imagesGB: 6.1,
      documentsGB: 1.6,
      backupsGB: 1.1,
      logsGB: 0.6,
    },
    lastUploadAt: 'Just now',
  },
  {
    businessId: 'biz_104',
    businessName: 'Downtown Express Bites',
    businessCode: 'BUS-104',
    planName: 'Basic Starter',
    usedGB: 3.2,
    quotaGB: 5,
    usagePercent: 64,
    status: 'normal',
    fileCount: 1150,
    categoryBreakdown: {
      imagesGB: 2.1,
      documentsGB: 0.6,
      backupsGB: 0.3,
      logsGB: 0.2,
    },
    lastUploadAt: '3 hours ago',
  },
  {
    businessId: 'biz_106',
    businessName: 'Bakehouse 360 Artisans',
    businessCode: 'BUS-106',
    planName: 'Enterprise Cloud',
    usedGB: 18.5,
    quotaGB: 50,
    usagePercent: 37,
    status: 'normal',
    fileCount: 7820,
    categoryBreakdown: {
      imagesGB: 11.2,
      documentsGB: 3.4,
      backupsGB: 2.6,
      logsGB: 1.3,
    },
    lastUploadAt: '20 mins ago',
  },
];
