import type { NotificationBroadcast } from './notification.types';

export const TARGET_BUSINESS_OPTIONS = [
  { id: 'biz_124', name: 'Al-Ahram Hospitality', plan: 'Enterprise' as const, userCount: 48 },
  { id: 'biz_102', name: 'Al-Baraka Retail', plan: 'Pro' as const, userCount: 26 },
  { id: 'biz_118', name: 'Golden Fork Gourmet', plan: 'Basic' as const, userCount: 14 },
  { id: 'biz_105', name: 'Nile Fresh Groceries', plan: 'Enterprise' as const, userCount: 62 },
  { id: 'biz_132', name: 'Cairo Tech Cafe', plan: 'Pro' as const, userCount: 18 },
  { id: 'biz_140', name: 'Express Burger Chain', plan: 'Enterprise' as const, userCount: 54 },
];

export const INITIAL_BROADCASTS: NotificationBroadcast[] = [
  {
    id: 'BRD-4902',
    title: 'Scheduled Platform Database Maintenance',
    message: 'We will be performing scheduled cloud database indexing and infrastructure maintenance tomorrow at 2:00 AM UTC. Estimated downtime is under 15 minutes. POS offline mode will remain operational.',
    type: 'maintenance',
    channels: ['in_app', 'email', 'push'],
    audience: {
      type: 'all_businesses',
      estimatedBusinessesCount: 148,
      estimatedUsersCount: 1840,
    },
    status: 'scheduled',
    scheduledAt: '2026-09-26T02:00:00Z',
    createdAt: '2026-09-25T08:30:00Z',
    authorName: 'Admin Ahmed',
    actionButton: {
      label: 'View Maintenance Roadmap',
      url: '/system/health',
    },
    metrics: {
      sentCount: 0,
      deliveredCount: 0,
      readCount: 0,
      clickCount: 0,
    },
  },
  {
    id: 'BRD-4890',
    title: 'Egyptian Tax Authority (ETA) e-Invoice V2.1 Deployment Live',
    message: 'All B2B and B2C sales receipts are now automatically cryptographic stamped with the mandatory 2026 ETA QR-code structure. No merchant action is required.',
    type: 'system_update',
    channels: ['in_app', 'email'],
    audience: {
      type: 'by_plan',
      plans: ['Pro', 'Enterprise'],
      estimatedBusinessesCount: 84,
      estimatedUsersCount: 920,
    },
    status: 'sent',
    sentAt: '2026-09-24T12:00:00Z',
    createdAt: '2026-09-24T11:45:00Z',
    authorName: 'Sarah Karim',
    actionButton: {
      label: 'Download Sample Tax Invoice',
      url: '/payments',
    },
    metrics: {
      sentCount: 920,
      deliveredCount: 914,
      readCount: 680,
      clickCount: 312,
    },
  },
  {
    id: 'BRD-4881',
    title: 'Urgent Security Notice: Rotate POS Cashier Terminal PINs',
    message: 'As part of our quarterly zero-trust security audit, all branch managers must instruct cashier staff to update their 4-digit POS station login PINs by end of week.',
    type: 'security_alert',
    channels: ['in_app', 'push'],
    audience: {
      type: 'by_role',
      roles: ['Branch Managers', 'Cashiers'],
      estimatedBusinessesCount: 120,
      estimatedUsersCount: 1140,
    },
    status: 'sent',
    sentAt: '2026-09-23T09:15:00Z',
    createdAt: '2026-09-23T09:00:00Z',
    authorName: 'Alex Morgan',
    actionButton: {
      label: 'Open Security Console',
      url: '/users',
    },
    metrics: {
      sentCount: 1140,
      deliveredCount: 1128,
      readCount: 940,
      clickCount: 520,
    },
  },
  {
    id: 'BRD-4870',
    title: 'Enterprise Exclusive: Dedicated Read-Replica Nodes Available',
    message: 'High-frequency reporting tenants on Enterprise tier can now request dedicated PostgreSQL read-replicas for analytical and custom PowerBI/Grafana dashboards with zero primary load.',
    type: 'promotional',
    channels: ['email'],
    audience: {
      type: 'by_plan',
      plans: ['Enterprise'],
      estimatedBusinessesCount: 22,
      estimatedUsersCount: 240,
    },
    status: 'sent',
    sentAt: '2026-09-21T15:00:00Z',
    createdAt: '2026-09-21T14:30:00Z',
    authorName: 'Alex Morgan',
    actionButton: {
      label: 'Request Replica Access',
      url: '/subscriptions',
    },
    metrics: {
      sentCount: 240,
      deliveredCount: 238,
      readCount: 195,
      clickCount: 88,
    },
  },
  {
    id: 'BRD-4862',
    title: 'Mobile POS App v4.2.0 Released on Apple App Store & Google Play',
    message: 'Includes offline sync resilience, Bluetooth receipt printing speed improvements, and faster barcode scanner auto-focus. Update your devices today.',
    type: 'general_info',
    channels: ['push', 'in_app'],
    audience: {
      type: 'specific_business',
      businessIds: ['biz_124', 'biz_102'],
      estimatedBusinessesCount: 2,
      estimatedUsersCount: 74,
    },
    status: 'sent',
    sentAt: '2026-09-19T10:00:00Z',
    createdAt: '2026-09-19T09:30:00Z',
    authorName: 'Sarah Karim',
    metrics: {
      sentCount: 74,
      deliveredCount: 74,
      readCount: 68,
      clickCount: 42,
    },
  },
];
