import type {
  RoleDefinition,
  AdminUser,
  AdminAccessLog,
  PermissionScope,
  PermissionAction
} from './admin.types';

export interface ScopeDescriptor {
  scope: PermissionScope;
  labelEn: string;
  labelAr: string;
  descEn: string;
  descAr: string;
  iconName: string;
  supportedActions: PermissionAction[];
}

export const PERMISSION_SCOPES: ScopeDescriptor[] = [
  {
    scope: 'tenants',
    labelEn: 'Tenants & Businesses',
    labelAr: 'المتاجر والمنشآت المشتركة',
    descEn: 'Directory of SaaS business accounts, onboarding approvals, domain bindings, and emergency tenant suspensions.',
    descAr: 'دليل منشآت المنصة، اعتماد المتاجر، ربط النطاقات، وتجميد المنشآت عند الطوارئ.',
    iconName: 'Building2',
    supportedActions: ['view', 'create', 'edit', 'delete', 'execute'],
  },
  {
    scope: 'subscriptions',
    labelEn: 'Subscriptions & SaaS Plans',
    labelAr: 'الاشتراكات وباقات الخدمة',
    descEn: 'Plan tiers (Free, Basic, Pro, Enterprise), custom quotes, feature quotas, and billing cycle overrides.',
    descAr: 'باقات الخدمة السحابية، الحصص التشغيلية، التخفيضات الاستثنائية، وفترات التجديد.',
    iconName: 'CreditCard',
    supportedActions: ['view', 'create', 'edit', 'delete', 'execute'],
  },
  {
    scope: 'finance',
    labelEn: 'Finance & Gateway Billing',
    labelAr: 'المالية وبوابات الدفع',
    descEn: 'Platform MRR/ARR analytics, Stripe/Paymob gateway credentials, invoice generation, and refund approvals.',
    descAr: 'إيرادات المنصة، بوابات الدفع الإلكتروني، إصدار الفواتير، واعتماد المبالغ المستردة.',
    iconName: 'Receipt',
    supportedActions: ['view', 'create', 'edit', 'delete', 'execute'],
  },
  {
    scope: 'platform_users',
    labelEn: 'Cross-Tenant Platform Users',
    labelAr: 'مستخدمو المنشآت الشاملين',
    descEn: 'Inspect business owners, branch managers, cashiers, force session invalidation, and password resets.',
    descAr: 'استعراض مالكي المتاجر، مديري الفروع، الكاشيرات، وإنهاء الجلسات المشبوهة.',
    iconName: 'Users',
    supportedActions: ['view', 'create', 'edit', 'delete', 'execute'],
  },
  {
    scope: 'support',
    labelEn: 'Support Desk & Tickets',
    labelAr: 'الدعم الفني والتذاكر',
    descEn: 'Triage customer inquiries, internal escalation notes, SLA tracking, and ticket status closures.',
    descAr: 'معالجة استفسارات العملاء، الملاحظات الداخلية السرية، وتتبع مؤشرات سرعة الرد.',
    iconName: 'Ticket',
    supportedActions: ['view', 'create', 'edit', 'delete', 'execute'],
  },
  {
    scope: 'notifications',
    labelEn: 'Broadcasts & Announcements',
    labelAr: 'الإشعارات والبث العام',
    descEn: 'Platform-wide push notifications, emergency maintenance banners, and targeted email releases.',
    descAr: 'إرسال التنبيهات الفورية للجوال، أشرطة الصيانة العاجلة، وحملات البريد الإلكتروني.',
    iconName: 'Bell',
    supportedActions: ['view', 'create', 'edit', 'delete', 'execute'],
  },
  {
    scope: 'audit_logs',
    labelEn: 'Platform Audit & Compliance',
    labelAr: 'سجلات المراجعة والامتثال',
    descEn: 'System activity telemetry, forensic inspection, actor tracking, and SOC2 compliance exports.',
    descAr: 'تتبع كافة الحركات الحساسة بالمنصة، التحليل الأمني الجنائي، وتصدير تقارير الامتثال.',
    iconName: 'ScrollText',
    supportedActions: ['view', 'execute'],
  },
  {
    scope: 'admin_management',
    labelEn: 'Internal Staff & RBAC',
    labelAr: 'إدارة المشرفين والصلاحيات',
    descEn: 'Invite internal operators, configure custom roles, define permission matrices, and security clearances.',
    descAr: 'دعوة موظفي إدارة المنصة، تخصيص مصفوفة الصلاحيات، وإدارة مفاتيح الأمان.',
    iconName: 'ShieldAlert',
    supportedActions: ['view', 'create', 'edit', 'delete', 'execute'],
  },
  {
    scope: 'system_infrastructure',
    labelEn: 'Infrastructure & Engine Health',
    labelAr: 'البنية التحتية وصحة النظام',
    descEn: 'Feature toggles, Redis cache flushes, PostgreSQL replica lag, backups, and maintenance triggers.',
    descAr: 'التحكم بمفاتيح الميزات، تفريغ كاش Redis، مراقبة قواعد البيانات، وتفعيل وضع الصيانة.',
    iconName: 'Server',
    supportedActions: ['view', 'create', 'edit', 'execute'],
  },
];

export const INITIAL_ROLES: RoleDefinition[] = [
  {
    id: 'role-super-admin',
    key: 'super_admin',
    name: 'Super Admin',
    nameAr: 'المسؤول السيادي الأكبر',
    description: 'Unrestricted sovereign root clearance. Manages security keys, platform staff, and infrastructure.',
    descriptionAr: 'صلاحيات سيادية غير مقيدة على كافة مفاصل النظام والبنية التحتية والمشرفين.',
    department: 'Executive Engineering',
    departmentAr: 'الإدارة التنفيذية والتقنية',
    clearanceLevel: 0,
    memberCount: 2,
    badgeColor: 'border-amber-500/30 bg-amber-500/10 text-amber-400',
    isSystem: true,
    permissions: {
      tenants: ['view', 'create', 'edit', 'delete', 'execute'],
      subscriptions: ['view', 'create', 'edit', 'delete', 'execute'],
      finance: ['view', 'create', 'edit', 'delete', 'execute'],
      platform_users: ['view', 'create', 'edit', 'delete', 'execute'],
      support: ['view', 'create', 'edit', 'delete', 'execute'],
      notifications: ['view', 'create', 'edit', 'delete', 'execute'],
      audit_logs: ['view', 'execute'],
      admin_management: ['view', 'create', 'edit', 'delete', 'execute'],
      system_infrastructure: ['view', 'create', 'edit', 'execute'],
    },
  },
  {
    id: 'role-finance-admin',
    key: 'finance_admin',
    name: 'Finance Admin',
    nameAr: 'مشرف المالية والحسابات',
    description: 'Manages platform revenue, gateway integrations, payouts, invoices, and refund authorizations.',
    descriptionAr: 'إدارة تدفقات الإيرادات، ربط بوابات الدفع، الفواتير، واعتماد المبالغ المستردة للعملاء.',
    department: 'Financial Operations',
    departmentAr: 'العمليات المالية والمحاسبية',
    clearanceLevel: 1,
    memberCount: 3,
    badgeColor: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-400',
    isSystem: true,
    permissions: {
      tenants: ['view'],
      subscriptions: ['view', 'edit', 'execute'],
      finance: ['view', 'create', 'edit', 'delete', 'execute'],
      platform_users: ['view'],
      support: ['view'],
      notifications: ['view'],
      audit_logs: ['view'],
      admin_management: [],
      system_infrastructure: [],
    },
  },
  {
    id: 'role-operations-admin',
    key: 'operations_admin',
    name: 'Operations Admin',
    nameAr: 'مشرف العمليات والاستقرار',
    description: 'Oversees platform health, onboarding workflows, database snapshots, and tenant compliance.',
    descriptionAr: 'متابعة استقرار المنصة، اعتماد المتاجر الجديدة، إدارة النسخ الاحتياطي، وحل الاختناقات.',
    department: 'DevOps & Site Reliability',
    departmentAr: 'استقرار النظم وهندسة العمليات',
    clearanceLevel: 1,
    memberCount: 2,
    badgeColor: 'border-cyan-500/30 bg-cyan-500/10 text-cyan-400',
    isSystem: true,
    permissions: {
      tenants: ['view', 'create', 'edit', 'execute'],
      subscriptions: ['view', 'edit'],
      finance: ['view'],
      platform_users: ['view', 'edit', 'execute'],
      support: ['view', 'edit'],
      notifications: ['view', 'create', 'execute'],
      audit_logs: ['view', 'execute'],
      admin_management: ['view'],
      system_infrastructure: ['view', 'create', 'edit', 'execute'],
    },
  },
  {
    id: 'role-support-admin',
    key: 'support_admin',
    name: 'Support Admin',
    nameAr: 'مشرف الدعم الفني وتجربة العميل',
    description: 'Triage business tickets, customer escalations, staff internal notes, and tenant read-only diagnosis.',
    descriptionAr: 'معالجة تذاكر الدعم، تصعيد المشكلات، كتابة الملاحظات الداخلية، وفحص شكاوى المتاجر.',
    department: 'Customer Experience',
    departmentAr: 'تجربة العملاء وخدمة المشتركين',
    clearanceLevel: 2,
    memberCount: 3,
    badgeColor: 'border-indigo-500/30 bg-indigo-500/10 text-indigo-400',
    isSystem: true,
    permissions: {
      tenants: ['view'],
      subscriptions: ['view'],
      finance: [],
      platform_users: ['view', 'edit'],
      support: ['view', 'create', 'edit', 'execute'],
      notifications: ['view'],
      audit_logs: [],
      admin_management: [],
      system_infrastructure: [],
    },
  },
  {
    id: 'role-content-admin',
    key: 'content_admin',
    name: 'Content Admin',
    nameAr: 'مشرف المحتوى والتواصل',
    description: 'Manages platform-wide announcements, maintenance schedules, knowledge base, and push campaigns.',
    descriptionAr: 'إدارة رسائل البث العام، جدولة إعلانات الصيانة، الحملات البريدية، ومقالات مركز المساعدة.',
    department: 'Product Marketing & Comms',
    departmentAr: 'التواصل والاتصال المؤسسي',
    clearanceLevel: 2,
    memberCount: 1,
    badgeColor: 'border-purple-500/30 bg-purple-500/10 text-purple-400',
    isSystem: true,
    permissions: {
      tenants: ['view'],
      subscriptions: ['view'],
      finance: [],
      platform_users: ['view'],
      support: ['view'],
      notifications: ['view', 'create', 'edit', 'delete', 'execute'],
      audit_logs: [],
      admin_management: [],
      system_infrastructure: [],
    },
  },
];

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'adm-001',
    name: 'Ahmed El-Sayed',
    email: 'ahmed.elsayed@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    roleKey: 'super_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'security_key',
    lastActive: '2026-09-25T09:24:10Z',
    lastLoginIp: '197.165.22.84',
    location: 'Cairo, Egypt',
    activeSessionsCount: 2,
    createdDate: '2025-01-10',
  },
  {
    id: 'adm-002',
    name: 'Sara Al-Mansoor',
    email: 'sara.mansoor@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    roleKey: 'super_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'security_key',
    lastActive: '2026-09-25T08:15:30Z',
    lastLoginIp: '94.200.11.45',
    location: 'Dubai, UAE',
    activeSessionsCount: 1,
    createdDate: '2025-01-15',
  },
  {
    id: 'adm-003',
    name: 'Ziad Mostafa',
    email: 'ziad.mostafa@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    roleKey: 'finance_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-25T09:12:00Z',
    lastLoginIp: '156.210.89.12',
    location: 'Cairo, Egypt',
    activeSessionsCount: 1,
    createdDate: '2025-03-01',
  },
  {
    id: 'adm-004',
    name: 'Hoda Farouk',
    email: 'hoda.farouk@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    roleKey: 'finance_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-24T18:40:22Z',
    lastLoginIp: '197.162.45.19',
    location: 'Alexandria, Egypt',
    activeSessionsCount: 1,
    createdDate: '2025-04-12',
  },
  {
    id: 'adm-005',
    name: 'Omar Hassan',
    email: 'omar.hassan@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    roleKey: 'operations_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'security_key',
    lastActive: '2026-09-25T09:30:45Z',
    lastLoginIp: '18.192.80.11',
    location: 'Frankfurt, Germany',
    activeSessionsCount: 2,
    createdDate: '2025-02-20',
  },
  {
    id: 'adm-006',
    name: 'Tamer Samir',
    email: 'tamer.samir@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    roleKey: 'operations_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-25T07:55:10Z',
    lastLoginIp: '41.233.104.98',
    location: 'Giza, Egypt',
    activeSessionsCount: 1,
    createdDate: '2025-05-18',
  },
  {
    id: 'adm-007',
    name: 'Karim Nabil',
    email: 'karim.nabil@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    roleKey: 'support_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-25T09:20:00Z',
    lastLoginIp: '156.198.34.12',
    location: 'Mansoura, Egypt',
    activeSessionsCount: 1,
    createdDate: '2025-06-01',
  },
  {
    id: 'adm-008',
    name: 'Maya Tarek',
    email: 'maya.tarek@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    roleKey: 'support_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-25T08:50:11Z',
    lastLoginIp: '197.166.72.33',
    location: 'Cairo, Egypt',
    activeSessionsCount: 1,
    createdDate: '2025-07-14',
  },
  {
    id: 'adm-009',
    name: 'Layla Radwan',
    email: 'layla.radwan@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a171edd2521d?auto=format&fit=crop&w=150&q=80',
    roleKey: 'content_admin',
    status: 'active',
    twoFactorEnabled: true,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-25T09:05:40Z',
    lastLoginIp: '212.118.140.21',
    location: 'Riyadh, Saudi Arabia',
    activeSessionsCount: 1,
    createdDate: '2025-08-01',
  },
  {
    id: 'adm-010',
    name: 'Youssef Kamel',
    email: 'youssef.kamel@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
    roleKey: 'support_admin',
    status: 'pending_invite',
    twoFactorEnabled: false,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-23T14:10:00Z',
    lastLoginIp: '-',
    location: 'Tanta, Egypt',
    activeSessionsCount: 0,
    createdDate: '2026-09-23',
  },
  {
    id: 'adm-011',
    name: 'Moustafa Refaat',
    email: 'moustafa.refaat@mot7km.io',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
    roleKey: 'finance_admin',
    status: 'suspended',
    twoFactorEnabled: true,
    twoFactorMethod: 'authenticator_app',
    lastActive: '2026-09-18T11:22:00Z',
    lastLoginIp: '197.165.99.14',
    location: 'Cairo, Egypt',
    activeSessionsCount: 0,
    createdDate: '2025-05-10',
  },
];

export const INITIAL_ACCESS_LOGS: AdminAccessLog[] = [
  {
    id: 'log-001',
    adminId: 'adm-001',
    adminName: 'Ahmed El-Sayed',
    adminRole: 'super_admin',
    action: 'Changed Role Clearance for Omar Hassan (Elevated permissions)',
    actionAr: 'تعديل مستوى الصلاحية للمشرف عمر حسن (ترقية الصلاحيات)',
    scope: 'admin_management',
    resourceTarget: 'Role: operations_admin',
    timestamp: '2026-09-25T09:24:10Z',
    ipAddress: '197.165.22.84',
    location: 'Cairo, Egypt',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/128.0',
    mfaVerified: true,
    status: 'success',
    riskScore: 'medium',
  },
  {
    id: 'log-002',
    adminId: 'adm-003',
    adminName: 'Ziad Mostafa',
    adminRole: 'finance_admin',
    action: 'Authorized refund of $4,500 to Nile Hypermarket (Tenant #104)',
    actionAr: 'اعتماد استرداد مالي بقيمة 4,500$ لمؤسسة أسواق النيل (منشأة #104)',
    scope: 'finance',
    resourceTarget: 'Refund #RF-9941',
    timestamp: '2026-09-25T09:12:00Z',
    ipAddress: '156.210.89.12',
    location: 'Cairo, Egypt',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/127.0',
    mfaVerified: true,
    status: 'success',
    riskScore: 'low',
  },
  {
    id: 'log-003',
    adminId: 'adm-005',
    adminName: 'Omar Hassan',
    adminRole: 'operations_admin',
    action: 'Triggered emergency DB snapshot & cache purge for European cluster',
    actionAr: 'تنفيذ لقطة احتياطية فورية لقاعدة البيانات وتفريغ كاش الخوادم الأوروبية',
    scope: 'system_infrastructure',
    resourceTarget: 'Cluster: eu-central-1',
    timestamp: '2026-09-25T09:01:22Z',
    ipAddress: '18.192.80.11',
    location: 'Frankfurt, Germany',
    userAgent: 'CLI / Antigravity Agent Daemon v2.4',
    mfaVerified: true,
    status: 'success',
    riskScore: 'medium',
  },
  {
    id: 'log-004',
    adminId: 'adm-009',
    adminName: 'Layla Radwan',
    adminRole: 'content_admin',
    action: 'Dispatched emergency maintenance notification: Scheduled DB upgrade',
    actionAr: 'إطلاق إشعار الصيانة العام: ترقية قواعد البيانات المجدولة',
    scope: 'notifications',
    resourceTarget: 'Broadcast #BC-2026-091',
    timestamp: '2026-09-25T08:55:00Z',
    ipAddress: '212.118.140.21',
    location: 'Riyadh, Saudi Arabia',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
    mfaVerified: true,
    status: 'success',
    riskScore: 'low',
  },
  {
    id: 'log-005',
    adminId: 'adm-007',
    adminName: 'Karim Nabil',
    adminRole: 'support_admin',
    action: 'Attempted to access Finance Revenue metrics (Access denied by RBAC)',
    actionAr: 'محاولة استعراض تقارير الإيرادات المالية (تم حظر الوصول عبر RBAC)',
    scope: 'finance',
    resourceTarget: 'Route: /payments/analytics',
    timestamp: '2026-09-25T08:42:15Z',
    ipAddress: '156.198.34.12',
    location: 'Mansoura, Egypt',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0) Safari/604.1',
    mfaVerified: true,
    status: 'blocked',
    riskScore: 'high',
  },
  {
    id: 'log-006',
    adminId: 'adm-002',
    adminName: 'Sara Al-Mansoor',
    adminRole: 'super_admin',
    action: 'Suspended internal admin Moustafa Refaat due to pending compliance audit',
    actionAr: 'تجميد حساب المشرف الداخلي مصطفى رفعت بانتظار استكمال التدقيق الأمني',
    scope: 'admin_management',
    resourceTarget: 'User: adm-011',
    timestamp: '2026-09-24T22:15:00Z',
    ipAddress: '94.200.11.45',
    location: 'Dubai, UAE',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/128.0',
    mfaVerified: true,
    status: 'success',
    riskScore: 'high',
  },
  {
    id: 'log-007',
    adminId: 'adm-008',
    adminName: 'Maya Tarek',
    adminRole: 'support_admin',
    action: 'Posted internal engineering escalation note on Ticket #TCK-1049',
    actionAr: 'إضافة ملاحظة هندسية داخلية عاجلة على التذكرة #TCK-1049',
    scope: 'support',
    resourceTarget: 'Ticket #TCK-1049',
    timestamp: '2026-09-24T19:10:30Z',
    ipAddress: '197.166.72.33',
    location: 'Cairo, Egypt',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
    mfaVerified: true,
    status: 'success',
    riskScore: 'low',
  },
];
