import type { SaaSPlan, Subscription, Coupon } from './subscriptions.types';

export const INITIAL_SAAS_PLANS: SaaSPlan[] = [
  {
    id: 'plan_free',
    tier: 'Free',
    name: 'Free Forever',
    tagline: 'Ideal for micro businesses, solopreneurs & initial product testing',
    taglineAr: 'مثالية للمشاريع الناشئة متناهية الصغر واختبار النظام',
    priceMonthly: 0,
    priceAnnual: 0,
    currency: 'USD',
    maxBranches: 1,
    maxEmployees: 3,
    maxProducts: 50,
    storageGb: 2,
    trialDays: 0,
    isPopular: false,
    subscribersCount: 42,
    limits: {
      apiCallsPerMonth: 1000,
      customDomains: false,
      prioritySupport: false,
      whiteLabel: false,
    },
    features: [
      { id: 'f1', name: 'Basic POS & Cloud Register', nameAr: 'نقاط بيع وسحابية أساسية', included: true },
      { id: 'f2', name: 'Single Branch Operations', nameAr: 'إدارة فرع واحد فقط', included: true },
      { id: 'f3', name: 'Standard Product Catalog', nameAr: 'كتالوج منتجات قياسي (50 منتج)', included: true },
      { id: 'f4', name: 'Community Support Desk', nameAr: 'دعم مجتمعي', included: true },
      { id: 'f5', name: 'Multi-branch Sync & Inventory Transfers', nameAr: 'مزامنة الفروع ومناقلات المخزون', included: false },
      { id: 'f6', name: 'Custom Domain & Root Whitelabel', nameAr: 'ربط نطاق خاص وإزالة شعار النظام', included: false },
      { id: 'f7', name: 'Rest API & Webhook Integrations', nameAr: 'واجهات برمجة التطبيقات والربط البرمجي', included: false },
    ],
  },
  {
    id: 'plan_basic',
    tier: 'Basic',
    name: 'Growth Starter',
    tagline: 'Essential infrastructure for single stores expanding to multi-branch',
    taglineAr: 'بنية تشغيلية متكاملة للمتاجر والمؤسسات المتنامية',
    priceMonthly: 49,
    priceAnnual: 39,
    currency: 'USD',
    maxBranches: 3,
    maxEmployees: 15,
    maxProducts: 1000,
    storageGb: 10,
    trialDays: 14,
    isPopular: false,
    subscribersCount: 128,
    limits: {
      apiCallsPerMonth: 25000,
      customDomains: true,
      prioritySupport: false,
      whiteLabel: false,
    },
    features: [
      { id: 'f1', name: 'Full POS & Barcode Scanner Engine', nameAr: 'نقاط بيع متقدمة وقارئ باركود سريع', included: true },
      { id: 'f2', name: 'Up to 3 Physical or Cloud Branches', nameAr: 'حتى 3 فروع حقيقية أو سحابية', included: true },
      { id: 'f3', name: '1,000 Inventory SKU Tracking', nameAr: 'إدارة وتتبع 1,000 منتج', included: true },
      { id: 'f4', name: 'Standard Email & Ticket Support (24h)', nameAr: 'دعم فني عبر التذاكر خلال 24 ساعة', included: true },
      { id: 'f5', name: 'Multi-branch Sync & Transfers', nameAr: 'مزامنة الفروع ومناقلات المخزون', included: true },
      { id: 'f6', name: 'Automated Daily Cloud Backups', nameAr: 'نسخ احتياطي سحابي يومي آلي', included: true },
      { id: 'f7', name: 'Rest API & Webhook Integrations', nameAr: 'واجهات برمجة التطبيقات والربط البرمجي', included: false },
    ],
  },
  {
    id: 'plan_pro',
    tier: 'Pro',
    name: 'Professional Business',
    tagline: 'High-performance scaling for multi-location enterprises and chains',
    taglineAr: 'أداء فائق وسرعة نمو لسلاسل الفروع والشركات المتوسطة',
    priceMonthly: 149,
    priceAnnual: 119,
    currency: 'USD',
    maxBranches: 10,
    maxEmployees: 60,
    maxProducts: 10000,
    storageGb: 50,
    trialDays: 14,
    isPopular: true,
    subscribersCount: 85,
    limits: {
      apiCallsPerMonth: 250000,
      customDomains: true,
      prioritySupport: true,
      whiteLabel: false,
    },
    features: [
      { id: 'f1', name: 'Everything in Basic included', nameAr: 'يشمل كافة مميزات باقة Basic', included: true },
      { id: 'f2', name: 'Up to 10 Branches & 60 Staff Members', nameAr: 'حتى 10 فروع و 60 موظف', included: true, highlight: true },
      { id: 'f3', name: 'Advanced BI Analytics & Forecast Engine', nameAr: 'تحليلات ذكاء أعمال متقدمة وتنبؤات', included: true },
      { id: 'f4', name: 'Full REST API & Webhooks Access', nameAr: 'وصول برمجى كامل للـ REST API والويب هوك', included: true, highlight: true },
      { id: 'f5', name: 'Custom Role-Based Granular Permissions', nameAr: 'تخصيص صلاحيات وأدوار الموظفين بدقة', included: true },
      { id: 'f6', name: 'Priority 24/7 SLA Support Desk', nameAr: 'دعم فني ذو أولوية على مدار الساعة', included: true },
      { id: 'f7', name: 'Custom Domain & SSL Automated Binding', nameAr: 'ربط نطاق مخصص وشهادة أمان تلقائية', included: true },
    ],
  },
  {
    id: 'plan_enterprise',
    tier: 'Enterprise',
    name: 'Sovereign Enterprise',
    tagline: 'Custom quota allocation, isolated infrastructure & root SLA guarantees',
    taglineAr: 'موارد غير محدودة وبنية تحتية مخصصة للشركات الكبرى والامتيازات',
    priceMonthly: 499,
    priceAnnual: 399,
    currency: 'USD',
    maxBranches: -1,
    maxEmployees: -1,
    maxProducts: -1,
    storageGb: 500,
    trialDays: 30,
    isPopular: false,
    subscribersCount: 19,
    limits: {
      apiCallsPerMonth: -1,
      customDomains: true,
      prioritySupport: true,
      whiteLabel: true,
    },
    features: [
      { id: 'f1', name: 'Unlimited Branches, Staff & SKUs', nameAr: 'فروع وموظفين ومنتجات غير محدودة', included: true, highlight: true },
      { id: 'f2', name: 'Dedicated High-IOPS Database Cluster', nameAr: 'قاعدة بيانات سحابية معزولة فائقة السرعة', included: true },
      { id: 'f3', name: '100% White-Label Branding & Mobile Apps', nameAr: 'واجهة مخصصة بالكامل بدون علامات تجارية', included: true, highlight: true },
      { id: 'f4', name: '99.99% Financial Uptime Guarantee (SLA)', nameAr: 'ضمان توافر وتشغيل 99.99% مالي ورسمي', included: true },
      { id: 'f5', name: 'Dedicated Technical Account Director', nameAr: 'مدير حساب تقني وخبير استشاري مخصص', included: true },
      { id: 'f6', name: 'Custom ERP & SAP/Oracle Integrations', nameAr: 'ربط مخصص مع أنظمة SAP و Oracle والجهات الحكومية', included: true },
      { id: 'f7', name: 'Sovereign Audit Vault & Regulatory Compliance', nameAr: 'خزينة تدقيق سيادية للامتثال الضريبي والأمني', included: true },
    ],
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub_101',
    businessId: 't-101',
    businessName: 'Gourmet Cloud Kitchens',
    subdomain: 'gourmet-cloud.mot7km.store',
    ownerName: 'Fahad Al-Otaibi',
    ownerEmail: 'f_otaibi@gourmetcloud.sa',
    planTier: 'Enterprise',
    billingCycle: 'annual',
    status: 'active',
    startDate: '2025-01-15',
    currentPeriodStart: '2026-01-15',
    currentPeriodEnd: '2027-01-15',
    autoRenew: true,
    pricePaid: 4788,
    discountApplied: {
      code: 'ANNUAL_20',
      percent: 20,
      amount: 1200,
    },
    branchesUsed: 14,
    branchesLimit: -1,
    employeesUsed: 68,
    employeesLimit: -1,
    mrrContribution: 399,
  },
  {
    id: 'sub_102',
    businessId: 't-102',
    businessName: 'Apex Logistics & Warehousing',
    subdomain: 'apex-logistics.mot7km.store',
    ownerName: 'Dr. Tariq Al-Ghamdi',
    ownerEmail: 'tariq@apexlogistics.sa',
    planTier: 'Pro',
    billingCycle: 'monthly',
    status: 'active',
    startDate: '2025-04-10',
    currentPeriodStart: '2026-09-10',
    currentPeriodEnd: '2026-10-10',
    autoRenew: true,
    pricePaid: 149,
    branchesUsed: 6,
    branchesLimit: 10,
    employeesUsed: 34,
    employeesLimit: 60,
    mrrContribution: 149,
  },
  {
    id: 'sub_103',
    businessId: 't-103',
    businessName: 'Luxe Perfumes & Cosmetics',
    subdomain: 'luxe-perfumes.mot7km.store',
    ownerName: 'Sara Al-Mansoor',
    ownerEmail: 'sara@luxeperfumes.ae',
    planTier: 'Pro',
    billingCycle: 'annual',
    status: 'active',
    startDate: '2025-06-01',
    currentPeriodStart: '2026-06-01',
    currentPeriodEnd: '2027-06-01',
    autoRenew: true,
    pricePaid: 1428,
    discountApplied: {
      code: 'RAMADAN2026',
      percent: 25,
      amount: 357,
    },
    customOverrides: {
      branchesLimitBonus: 2,
      employeesLimitBonus: 10,
      storageGbBonus: 20,
      gracePeriodDays: 14,
      notes: 'Granted 2 extra branches bonus for rapid Dubai mall expansion',
    },
    branchesUsed: 8,
    branchesLimit: 12,
    employeesUsed: 42,
    employeesLimit: 70,
    mrrContribution: 119,
  },
  {
    id: 'sub_104',
    businessId: 't-104',
    businessName: 'Al-Ahram Hospitality Group',
    subdomain: 'ahram-hospitality.mot7km.store',
    ownerName: 'Nader Roushdy',
    ownerEmail: 'n.roushdy@ahramgroup.eg',
    planTier: 'Enterprise',
    billingCycle: 'monthly',
    status: 'trial',
    startDate: '2026-09-18',
    currentPeriodStart: '2026-09-18',
    currentPeriodEnd: '2026-10-02',
    trialEndsAt: '2026-10-02',
    autoRenew: false,
    pricePaid: 0,
    branchesUsed: 6,
    branchesLimit: 20,
    employeesUsed: 38,
    employeesLimit: 120,
    mrrContribution: 499,
  },
  {
    id: 'sub_105',
    businessId: 't-105',
    businessName: 'Delta Med Pharma Solutions',
    subdomain: 'delta-pharma.mot7km.store',
    ownerName: 'Dr. Mahmoud Ezzat',
    ownerEmail: 'm.ezzat@deltapharma.eg',
    planTier: 'Basic',
    billingCycle: 'monthly',
    status: 'pending_renewal',
    startDate: '2025-09-28',
    currentPeriodStart: '2026-08-28',
    currentPeriodEnd: '2026-09-28',
    autoRenew: false,
    pricePaid: 49,
    branchesUsed: 3,
    branchesLimit: 3,
    employeesUsed: 12,
    employeesLimit: 15,
    mrrContribution: 49,
  },
  {
    id: 'sub_106',
    businessId: 't-106',
    businessName: 'Horizon Auto Parts Direct',
    subdomain: 'horizon-auto.mot7km.store',
    ownerName: 'Khalid Al-Dosari',
    ownerEmail: 'khalid@horizonauto.sa',
    planTier: 'Pro',
    billingCycle: 'monthly',
    status: 'expired',
    startDate: '2025-05-12',
    currentPeriodStart: '2026-07-12',
    currentPeriodEnd: '2026-08-12',
    autoRenew: false,
    pricePaid: 149,
    branchesUsed: 2,
    branchesLimit: 10,
    employeesUsed: 16,
    employeesLimit: 60,
    mrrContribution: 149,
  },
  {
    id: 'sub_107',
    businessId: 't-107',
    businessName: 'Nile Artisan Bakeries',
    subdomain: 'nile-bakeries.mot7km.store',
    ownerName: 'Sherif El-Masry',
    ownerEmail: 'sherif@nilebakeries.eg',
    planTier: 'Basic',
    billingCycle: 'annual',
    status: 'cancelled',
    startDate: '2025-02-01',
    currentPeriodStart: '2026-02-01',
    currentPeriodEnd: '2026-08-30',
    autoRenew: false,
    pricePaid: 468,
    branchesUsed: 2,
    branchesLimit: 3,
    employeesUsed: 9,
    employeesLimit: 15,
    mrrContribution: 39,
  },
  {
    id: 'sub_108',
    businessId: 't-108',
    businessName: 'Arabian Oasis Supermarkets',
    subdomain: 'oasis-markets.mot7km.store',
    ownerName: 'Rashid Al-Kuwari',
    ownerEmail: 'rashid@oasismarkets.qa',
    planTier: 'Enterprise',
    billingCycle: 'annual',
    status: 'active',
    startDate: '2024-11-01',
    currentPeriodStart: '2025-11-01',
    currentPeriodEnd: '2026-11-01',
    autoRenew: true,
    pricePaid: 4788,
    branchesUsed: 18,
    branchesLimit: -1,
    employeesUsed: 94,
    employeesLimit: -1,
    mrrContribution: 399,
  },
  {
    id: 'sub_109',
    businessId: 't-109',
    businessName: 'Velocity Sports Apparel',
    subdomain: 'velocity-fit.mot7km.store',
    ownerName: 'Karim Zaki',
    ownerEmail: 'karim@velocityfit.ae',
    planTier: 'Basic',
    billingCycle: 'monthly',
    status: 'active',
    startDate: '2026-02-14',
    currentPeriodStart: '2026-09-14',
    currentPeriodEnd: '2026-10-14',
    autoRenew: true,
    pricePaid: 49,
    branchesUsed: 2,
    branchesLimit: 3,
    employeesUsed: 8,
    employeesLimit: 15,
    mrrContribution: 49,
  },
  {
    id: 'sub_110',
    businessId: 't-110',
    businessName: 'Zenith Tech Electronics',
    subdomain: 'zenith-tech.mot7km.store',
    ownerName: 'Yousef Al-Harbi',
    ownerEmail: 'yousef@zenithtech.sa',
    planTier: 'Free',
    billingCycle: 'monthly',
    status: 'active',
    startDate: '2026-03-01',
    currentPeriodStart: '2026-09-01',
    currentPeriodEnd: '2027-03-01',
    autoRenew: true,
    pricePaid: 0,
    branchesUsed: 1,
    branchesLimit: 1,
    employeesUsed: 2,
    employeesLimit: 3,
    mrrContribution: 0,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'cpn_1',
    code: 'LAUNCH50',
    description: '50% discount on initial Pro or Enterprise subscription for 3 billing cycles',
    discountType: 'percentage',
    discountValue: 50,
    validPlans: ['Pro', 'Enterprise'],
    maxRedemptions: 100,
    redemptionsCount: 38,
    expiresAt: '2026-12-31',
    isActive: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'cpn_2',
    code: 'RAMADAN2026',
    description: '25% seasonal blessing discount across all annual subscription tiers',
    discountType: 'percentage',
    discountValue: 25,
    validPlans: ['Basic', 'Pro', 'Enterprise'],
    maxRedemptions: 250,
    redemptionsCount: 84,
    expiresAt: '2026-11-15',
    isActive: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'cpn_3',
    code: 'START20',
    description: '$20 flat voucher for newly registered startups moving from Free to Basic',
    discountType: 'fixed',
    discountValue: 20,
    validPlans: ['Basic'],
    maxRedemptions: 500,
    redemptionsCount: 162,
    expiresAt: '2026-10-31',
    isActive: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'cpn_4',
    code: 'FOUNDERS_VIP',
    description: 'Exclusive 40% recurring discount for initial pilot clients & VIP partners',
    discountType: 'percentage',
    discountValue: 40,
    validPlans: ['Pro', 'Enterprise'],
    maxRedemptions: 20,
    redemptionsCount: 20,
    expiresAt: '2026-06-30',
    isActive: false,
    createdAt: '2025-06-01',
  },
];
