import type { IntegrationItem, WebhookEventLog, IntegrationsKpiSummary } from './integrations.types';

export const INITIAL_INTEGRATIONS_DATA: IntegrationItem[] = [
  {
    id: 'int-stripe',
    name: 'Stripe Payments',
    providerKey: 'stripe',
    category: 'payment',
    descriptionEn: 'Global credit cards, Apple Pay, SEPA, and international subscription processing.',
    descriptionAr: 'معالجة بطاقات الائتمان الدولية و Apple Pay والاشتراكات السحابية المتكررة.',
    status: 'connected',
    environment: 'production',
    healthScore: 99.98,
    latencyMs: 42,
    monthlyUsage: 312450,
    monthlyLimit: null,
    usageUnit: 'USD',
    maskedKey: 'pk_live_51Mv9••••••••984a',
    webhookUrl: 'https://api.mot7km.com/v1/webhooks/stripe',
    lastSyncAt: '2 mins ago',
  },
  {
    id: 'int-moyasar',
    name: 'Moyasar Gateway',
    providerKey: 'moyasar',
    category: 'payment',
    descriptionEn: 'Saudi Arabia national payment gateway supporting Mada, Apple Pay, and STC Pay.',
    descriptionAr: 'بوابة الدفع الوطنية السعودية الداعمة لبطاقات مدى، أبل باي، و STC Pay.',
    status: 'connected',
    environment: 'production',
    healthScore: 99.92,
    latencyMs: 38,
    monthlyUsage: 435800,
    monthlyLimit: null,
    usageUnit: 'SAR',
    maskedKey: 'pk_live_my_••••••••663f',
    webhookUrl: 'https://api.mot7km.com/v1/webhooks/moyasar',
    lastSyncAt: 'Just now',
  },
  {
    id: 'int-tap',
    name: 'Tap Payments GCC',
    providerKey: 'tap',
    category: 'payment',
    descriptionEn: 'Regional GCC payment rail covering KNET (Kuwait), Benefit (Bahrain), and UAE cards.',
    descriptionAr: 'بوابة الدفع الخليجية الداعمة لكي نت البحرين وبنفت الكويت وبطاقات الإمارات.',
    status: 'sandbox',
    environment: 'sandbox',
    healthScore: 98.7,
    latencyMs: 65,
    monthlyUsage: 14200,
    monthlyLimit: null,
    usageUnit: 'SAR',
    maskedKey: 'pk_test_tap_••••••••811d',
    webhookUrl: 'https://staging.mot7km.com/v1/webhooks/tap',
    lastSyncAt: '15 mins ago',
  },
  {
    id: 'int-fcm',
    name: 'Firebase Cloud Messaging (FCM)',
    providerKey: 'fcm',
    category: 'messaging',
    descriptionEn: 'Real-time low-latency push notifications for POS terminals and customer order screens.',
    descriptionAr: 'إشعارات لحظية فائقة السرعة لشاشات نقاط البيع (POS) وتطبيقات المستهلكين.',
    status: 'connected',
    environment: 'production',
    healthScore: 99.99,
    latencyMs: 24,
    monthlyUsage: 890400,
    monthlyLimit: 2000000,
    usageUnit: 'Pushes',
    maskedKey: 'AAAA••••••••kR92',
    webhookUrl: 'https://api.mot7km.com/v1/notifications/fcm/ack',
    lastSyncAt: '1 min ago',
  },
  {
    id: 'int-twilio',
    name: 'Twilio SMS & OTP',
    providerKey: 'twilio',
    category: 'messaging',
    descriptionEn: 'Two-factor OTP dispatch, cashier PIN resets, and urgent order update SMS alerts.',
    descriptionAr: 'إرسال رموز التحقق OTP ورسائل استعادة كلمة المرور وإشعارات الطلبات الفورية.',
    status: 'connected',
    environment: 'production',
    healthScore: 99.65,
    latencyMs: 82,
    monthlyUsage: 64200,
    monthlyLimit: 100000,
    usageUnit: 'SMS',
    maskedKey: 'AC••••••••54a8b9',
    webhookUrl: 'https://api.mot7km.com/v1/webhooks/twilio/status',
    lastSyncAt: '8 mins ago',
  },
  {
    id: 'int-resend',
    name: 'Resend Transactional Email',
    providerKey: 'resend',
    category: 'messaging',
    descriptionEn: 'High-deliverability transactional receipts, monthly invoices, and tenant invitations.',
    descriptionAr: 'خدمة تسليم البريد الإلكتروني للفواتير الشهرية ودعوات الموظفين والتنبيهات الأمنية.',
    status: 'connected',
    environment: 'production',
    healthScore: 99.94,
    latencyMs: 51,
    monthlyUsage: 285400,
    monthlyLimit: 500000,
    usageUnit: 'Emails',
    maskedKey: 're_••••••••3982e0',
    webhookUrl: 'https://api.mot7km.com/v1/webhooks/resend/events',
    lastSyncAt: '3 mins ago',
  },
  {
    id: 'int-s3',
    name: 'AWS S3 Cloud Object Storage',
    providerKey: 's3',
    category: 'cloud',
    descriptionEn: 'Scalable cloud bucket hosting tenant menu media, avatars, and tax invoice archives.',
    descriptionAr: 'مستودع التخزين السحابي لصور المنتجات وقوائم الطعام وأرشيف الفواتير الضريبية.',
    status: 'connected',
    environment: 'production',
    healthScore: 100.0,
    latencyMs: 18,
    monthlyUsage: 11.8,
    monthlyLimit: 15.0,
    usageUnit: 'TB',
    maskedKey: 'AKIA••••••••77LQ',
    webhookUrl: 'arn:aws:s3:::mot7km-prod-storage',
    lastSyncAt: 'Just now',
  },
  {
    id: 'int-gmaps',
    name: 'Google Maps Platform',
    providerKey: 'google_maps',
    category: 'cloud',
    descriptionEn: 'Geocoding, delivery zone polygon validation, and tenant branch map rendering.',
    descriptionAr: 'تحديد النطاقات الجغرافية لفروع المتاجر ومناطق التوصيل والترميز الجغرافي للعناوين.',
    status: 'connected',
    environment: 'production',
    healthScore: 99.88,
    latencyMs: 34,
    monthlyUsage: 412000,
    monthlyLimit: 1000000,
    usageUnit: 'Queries',
    maskedKey: 'AIza••••••••881b',
    webhookUrl: 'https://maps.googleapis.com/maps/api',
    lastSyncAt: '5 mins ago',
  },
  {
    id: 'int-zatca',
    name: 'ZATCA Phase 2 Clearance Engine',
    providerKey: 'zatca',
    category: 'webhooks',
    descriptionEn: 'Cryptographic compliance clearance and XML hash stamping with Saudi Tax Authority.',
    descriptionAr: 'الربط المباشر مع هيئة الزكاة والضريبة والجمارك لاعتماد الفواتير الإلكترونية مشفرة.',
    status: 'connected',
    environment: 'production',
    healthScore: 99.75,
    latencyMs: 115,
    monthlyUsage: 198400,
    monthlyLimit: null,
    usageUnit: 'Cleared Invoices',
    maskedKey: 'CSID_••••••••2918',
    webhookUrl: 'https://api.mot7km.com/v1/tax/zatca/webhook',
    lastSyncAt: '10 mins ago',
  },
];

export const MOCK_WEBHOOK_LOGS: WebhookEventLog[] = [
  {
    id: 'wh-log-901',
    event: 'invoice.zatca.cleared',
    targetProvider: 'ZATCA E-Invoicing',
    endpoint: 'https://api.mot7km.com/v1/tax/zatca/webhook',
    statusCode: 200,
    status: 'success',
    timestamp: '2 mins ago',
    durationMs: 118,
    payloadSummary: 'UUID: 8f9b-11ec | Hash: a7e3...9b | Tenant: BUS-101',
  },
  {
    id: 'wh-log-902',
    event: 'payment_intent.succeeded',
    targetProvider: 'Moyasar Gateway',
    endpoint: 'https://api.mot7km.com/v1/webhooks/moyasar',
    statusCode: 200,
    status: 'success',
    timestamp: '5 mins ago',
    durationMs: 44,
    payloadSummary: 'Amount: 185.00 SAR | Method: mada | Order: #ORD-7712',
  },
  {
    id: 'wh-log-903',
    event: 'message.sms.delivered',
    targetProvider: 'Twilio SMS & OTP',
    endpoint: 'https://api.mot7km.com/v1/webhooks/twilio/status',
    statusCode: 200,
    status: 'success',
    timestamp: '9 mins ago',
    durationMs: 76,
    payloadSummary: 'Recipient: +96650••••91 | Type: Cashier_PIN_Reset',
  },
  {
    id: 'wh-log-904',
    event: 'subscription.renewed',
    targetProvider: 'Stripe Payments',
    endpoint: 'https://api.mot7km.com/v1/webhooks/stripe',
    statusCode: 200,
    status: 'success',
    timestamp: '14 mins ago',
    durationMs: 38,
    payloadSummary: 'Sub: sub_1882a | Plan: Enterprise | Tenant: BUS-102',
  },
  {
    id: 'wh-log-905',
    event: 'charge.tap.webhook',
    targetProvider: 'Tap Payments GCC',
    endpoint: 'https://staging.mot7km.com/v1/webhooks/tap',
    statusCode: 200,
    status: 'success',
    timestamp: '22 mins ago',
    durationMs: 62,
    payloadSummary: 'Sandbox Auth | KNET Simulation | Status: CAPTURED',
  },
];

export const INITIAL_INTEGRATIONS_KPIS: IntegrationsKpiSummary = {
  totalConnected: 8,
  inSandbox: 1,
  systemHealthIndex: 99.88,
  monthlyPaymentVolumeUsd: 428500,
  monthlyMessagesDispatched: 1240000,
};
