import type { SystemAnnouncement, ApiEndpointHealth } from './announcements.types';

export const INITIAL_ANNOUNCEMENTS: SystemAnnouncement[] = [
  {
    id: 'anc_001',
    title: 'AI Smart Demand Restocking is Now Live!',
    titleAr: 'ميزة التنبؤ الذكي بنفاد المخزون وإعادة الطلب أصبحت متاحة الآن!',
    message: 'All subscribers can now enable automated ingredient spoilage prediction and smart vendor purchase order generation directly from the inventory dashboard.',
    messageAr: 'يمكن لجميع المشتركين الآن تفعيل التنبؤ الآلي بصلاحية واستهلاك المكونات وإنشاء مسودات أوامر الشراء الذكية مباشرة من لوحة المخزون.',
    type: 'success',
    audience: 'everyone',
    targetIds: [],
    targetLabels: ['All Tenants'],
    isActive: true,
    isDismissible: true,
    isPinned: true,
    actionUrl: '/inventory',
    actionText: 'Explore Feature',
    actionTextAr: 'استكشف الميزة',
    startDate: '2026-09-20',
    createdAt: '2026-09-20 10:00 AM',
    createdBy: 'Ahmed Tariq (Lead Architect)',
  },
  {
    id: 'anc_002',
    title: 'Scheduled Cloud Infrastructure Upgrade Notice',
    titleAr: 'تنبيه: أعمال ترقية مجدولة في البنية التحتية السحابية',
    message: 'We will be conducting database index optimizations on Sunday at 03:00 AM GMT+3. You may experience brief latency spikes for approximately 10 minutes.',
    messageAr: 'سنقوم بإجراء تحسينات وفهارس لقواعد البيانات يوم الأحد الساعة 03:00 صباحاً بتوقيت مكة المكرمة. قد تلاحظون بطئاً طفيفاً لمدة لا تتجاوز 10 دقائق.',
    type: 'warning',
    audience: 'plans',
    targetIds: ['plan_pro', 'plan_enterprise'],
    targetLabels: ['Pro Business', 'Enterprise Cloud'],
    isActive: true,
    isDismissible: false,
    isPinned: false,
    actionUrl: '/system/health',
    actionText: 'System Status',
    actionTextAr: 'حالة الخوادم',
    startDate: '2026-09-24',
    endDate: '2026-09-28',
    createdAt: '2026-09-24 02:30 PM',
    createdBy: 'Karim Zidan (DevOps)',
  },
  {
    id: 'anc_003',
    title: 'Emergency: Mada Gateway Intermittent Network Issues',
    titleAr: 'تنبيه طارئ: تذبذب مؤقت في شبكة مدفوعات مدى',
    message: 'The local payment switchboard is experiencing intermittent gateway timeouts. Please advise cashiers to use fallback terminal mode if an initial payment fails.',
    messageAr: 'تشهد مقسمات المدفوعات المحلية تذبذباً مؤقتاً في معالجة العمليات. يرجى توجيه الكاشير لاستخدام وضع الاحتياط عند تعثر العملية للمرة الأولى.',
    type: 'critical',
    audience: 'everyone',
    targetIds: [],
    targetLabels: ['All Tenants'],
    isActive: false,
    isDismissible: false,
    isPinned: true,
    startDate: '2026-09-18',
    endDate: '2026-09-19',
    createdAt: '2026-09-18 08:15 AM',
    createdBy: 'Root Super Admin',
  },
  {
    id: 'anc_004',
    title: 'Exclusive Beta: Direct WhatsApp Storefront Ingestion',
    titleAr: 'تجربة بيتا حصرية: الطلب المباشر عبر المتجر وواتساب',
    message: 'Your business has been selected for our early-access WhatsApp ordering integration. Enjoy direct automated dispatching with zero external commission fees.',
    messageAr: 'تم اختيار نشاطكم التجاري للانضمام للنسخة التجريبية الحصرية للطلب عبر واتساب. استمتعوا باستقبال الطلبات تلقائياً وبدون أي عمولات خارجية.',
    type: 'info',
    audience: 'businesses',
    targetIds: ['biz_101', 'biz_102'],
    targetLabels: ['Al-Sultan Gourmet Grill', 'Café Nero Artisan'],
    isActive: true,
    isDismissible: true,
    isPinned: false,
    startDate: '2026-09-22',
    createdAt: '2026-09-22 04:00 PM',
    createdBy: 'Sara Nour (Product Mgr)',
  },
];

export const INITIAL_API_ENDPOINTS: ApiEndpointHealth[] = [
  {
    id: 'api_core',
    name: 'Core Multi-Tenant REST API',
    category: 'core',
    baseUrl: 'https://api.mot7km.store/v1',
    version: 'v1.8.4',
    status: 'healthy',
    responseTimeMs: 38,
    uptimePercentage: 99.98,
    rateLimitPerMinute: 1200,
    rateLimitUsagePercent: 42,
    corsAllowed: ['https://app.mot7km.store', 'https://pos.mot7km.store', 'https://admin.mot7km.store'],
    lastChecked: 'Just now',
  },
  {
    id: 'api_pos_stream',
    name: 'Cloud POS WebSocket Real-Time Gateway',
    category: 'pos',
    baseUrl: 'wss://pos-sync.mot7km.store/stream',
    version: 'v2.1.0',
    status: 'healthy',
    responseTimeMs: 22,
    uptimePercentage: 99.99,
    rateLimitPerMinute: 5000,
    rateLimitUsagePercent: 68,
    corsAllowed: ['https://pos.mot7km.store', 'https://terminal.mot7km.store'],
    lastChecked: 'Just now',
  },
  {
    id: 'api_webhooks',
    name: 'Webhook Event Dispatcher & Payment Receiver',
    category: 'payments',
    baseUrl: 'https://webhooks.mot7km.store/events',
    version: 'v1.2.0',
    status: 'healthy',
    responseTimeMs: 54,
    uptimePercentage: 99.95,
    rateLimitPerMinute: 2000,
    rateLimitUsagePercent: 31,
    corsAllowed: ['*'],
    lastChecked: 'Just now',
  },
  {
    id: 'api_kds',
    name: 'Kitchen Display Audio/Visual Stream Engine',
    category: 'orders',
    baseUrl: 'https://kds.mot7km.store/v1',
    version: 'v1.5.2',
    status: 'degraded',
    responseTimeMs: 210,
    uptimePercentage: 98.40,
    rateLimitPerMinute: 1000,
    rateLimitUsagePercent: 84,
    corsAllowed: ['https://kds.mot7km.store'],
    lastChecked: '2 mins ago',
  },
  {
    id: 'api_ai',
    name: 'Predictive Restocking & Restock AI Engine',
    category: 'inventory',
    baseUrl: 'https://ai.mot7km.store/predict',
    version: 'v0.9.1-beta',
    status: 'healthy',
    responseTimeMs: 120,
    uptimePercentage: 99.90,
    rateLimitPerMinute: 600,
    rateLimitUsagePercent: 25,
    corsAllowed: ['https://app.mot7km.store'],
    lastChecked: 'Just now',
  },
];
