import type { SupportTicket, SupportAdminStaff } from './support.types';

export const SUPPORT_ADMIN_STAFF: SupportAdminStaff[] = [
  {
    id: 'adm_ahmed',
    name: 'Admin Ahmed',
    email: 'ahmed.security@mot7km.com',
    role: 'Principal Security & Ops',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
    activeTicketsCount: 4,
  },
  {
    id: 'adm_sarah',
    name: 'Sarah Karim',
    email: 'sarah.k@mot7km.com',
    role: 'Senior ERP Solutions Engineer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
    activeTicketsCount: 3,
  },
  {
    id: 'adm_alex',
    name: 'Alex Morgan',
    email: 'superadmin@mot7km.com',
    role: 'Global Platform Admin',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&h=120&q=80',
    activeTicketsCount: 2,
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-8902',
    subject: 'Payment Gateway Timeout during high volume weekend sales',
    category: 'pos_hardware',
    priority: 'critical',
    status: 'open',
    businessId: 'biz_124',
    businessName: 'Al-Ahram Hospitality',
    businessPlan: 'Enterprise',
    customerContact: {
      name: 'Tariq Al-Masry',
      email: 'tariq@alahram-hospitality.com',
      phone: '+20 100 234 5678',
      role: 'General Manager',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80',
    },
    assignedTo: SUPPORT_ADMIN_STAFF[0], // Admin Ahmed
    createdAt: '2026-09-25T08:15:00Z',
    updatedAt: '2026-09-25T09:05:00Z',
    slaTargetAt: '2026-09-25T09:15:00Z', // 1h SLA
    isSlaBreached: false,
    tags: ['POS Gateway', 'Network Timeout', 'Enterprise SLA'],
    attachments: [
      {
        id: 'att_01',
        name: 'pos_error_screen_504.png',
        size: '1.4 MB',
        type: 'image',
        url: '#',
        uploadedAt: '2026-09-25T08:15:00Z',
      },
      {
        id: 'att_02',
        name: 'gateway_raw_dump.log',
        size: '420 KB',
        type: 'log',
        url: '#',
        uploadedAt: '2026-09-25T08:15:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_01',
        sender: {
          id: 'usr_tariq',
          name: 'Tariq Al-Masry',
          email: 'tariq@alahram-hospitality.com',
          role: 'General Manager',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: false,
        },
        body: 'Urgent! 3 of our main cashier stations in the Zamalek branch are failing transactions with error code GATEWAY_TIMEOUT_504. Line of customers is growing. Please investigate immediately!',
        timestamp: '2026-09-25T08:15:00Z',
        isInternal: false,
        attachments: [
          {
            id: 'att_01',
            name: 'pos_error_screen_504.png',
            size: '1.4 MB',
            type: 'image',
            url: '#',
            uploadedAt: '2026-09-25T08:15:00Z',
          },
        ],
      },
      {
        id: 'msg_02',
        sender: {
          id: 'adm_ahmed',
          name: 'Admin Ahmed',
          email: 'ahmed.security@mot7km.com',
          role: 'Principal Security & Ops',
          avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'Investigating right now. Checking Paymob and Geidea routing proxies for the Cairo cluster.',
        timestamp: '2026-09-25T08:24:00Z',
        isInternal: false,
      },
      {
        id: 'msg_03',
        sender: {
          id: 'adm_ahmed',
          name: 'Admin Ahmed',
          email: 'ahmed.security@mot7km.com',
          role: 'Principal Security & Ops',
          avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'INTERNAL NOTE: Found a TLS handshake stall on upstream proxy port 8443. Failing over traffic to the secondary standby gateway route. Tenant does not need to reboot POS terminals.',
        timestamp: '2026-09-25T08:40:00Z',
        isInternal: true,
      },
      {
        id: 'msg_04',
        sender: {
          id: 'adm_ahmed',
          name: 'Admin Ahmed',
          email: 'ahmed.security@mot7km.com',
          role: 'Principal Security & Ops',
          avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'Hello Tariq, we have seamlessly rerouted your payment traffic through our secondary secure node. Can you please process a 1 EGP test transaction on terminal #2 and confirm?',
        timestamp: '2026-09-25T09:05:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'TCK-8894',
    subject: 'Plan Upgrade to Pro tier not unlocking extra 5 branches quota',
    category: 'billing',
    priority: 'high',
    status: 'pending',
    businessId: 'biz_102',
    businessName: 'Al-Baraka Retail',
    businessPlan: 'Pro',
    customerContact: {
      name: 'Mahmoud Al-Baraka',
      email: 'mahmoud@albaraka-stores.com',
      phone: '+20 111 889 0012',
      role: 'Business Owner',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80',
    },
    assignedTo: SUPPORT_ADMIN_STAFF[1], // Sarah Karim
    createdAt: '2026-09-25T06:30:00Z',
    updatedAt: '2026-09-25T07:45:00Z',
    slaTargetAt: '2026-09-25T10:30:00Z',
    isSlaBreached: false,
    tags: ['Quota Lock', 'Stripe Webhook', 'Pro Tier'],
    attachments: [
      {
        id: 'att_03',
        name: 'invoice_receipt_inv_8829.pdf',
        size: '185 KB',
        type: 'pdf',
        url: '#',
        uploadedAt: '2026-09-25T06:30:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_05',
        sender: {
          id: 'usr_mahmoud',
          name: 'Mahmoud Al-Baraka',
          email: 'mahmoud@albaraka-stores.com',
          role: 'Business Owner',
          avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: false,
        },
        body: 'We completed payment for the Pro plan upgrade 2 hours ago (attached receipt). However, when our operations lead tries to register the 4th branch in Maadi, the system still shows "Branch quota reached (3/3)".',
        timestamp: '2026-09-25T06:30:00Z',
        isInternal: false,
      },
      {
        id: 'msg_06',
        sender: {
          id: 'adm_sarah',
          name: 'Sarah Karim',
          email: 'sarah.k@mot7km.com',
          role: 'Senior ERP Solutions Engineer',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'INTERNAL NOTE: Stripe webhook event invoice.payment_succeeded was acknowledged but the tenant Redis cache TTL did not invalidate the quota counter. Manually refreshed subscription claims.',
        timestamp: '2026-09-25T07:40:00Z',
        isInternal: true,
      },
      {
        id: 'msg_07',
        sender: {
          id: 'adm_sarah',
          name: 'Sarah Karim',
          email: 'sarah.k@mot7km.com',
          role: 'Senior ERP Solutions Engineer',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'Hello Mahmoud! Your subscription quota has been refreshed. You now have 8 branch slots enabled. Please log out and back into the dashboard or hard refresh (Ctrl + F5). Waiting for your confirmation.',
        timestamp: '2026-09-25T07:45:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'TCK-8889',
    subject: 'Cashier PIN lockouts after 3 consecutive wrong attempts',
    category: 'account',
    priority: 'medium',
    status: 'open',
    businessId: 'biz_118',
    businessName: 'Golden Fork Gourmet',
    businessPlan: 'Basic',
    customerContact: {
      name: 'Nadia Soliman',
      email: 'nadia@goldenfork.eg',
      phone: '+20 122 345 6789',
      role: 'Branch Manager',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&h=120&q=80',
    },
    assignedTo: undefined, // Unassigned
    createdAt: '2026-09-25T07:10:00Z',
    updatedAt: '2026-09-25T07:10:00Z',
    slaTargetAt: '2026-09-25T15:10:00Z',
    isSlaBreached: false,
    tags: ['Security PIN', 'POS Staff', 'Lockout'],
    attachments: [],
    messages: [
      {
        id: 'msg_08',
        sender: {
          id: 'usr_nadia',
          name: 'Nadia Soliman',
          email: 'nadia@goldenfork.eg',
          role: 'Branch Manager',
          avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: false,
        },
        body: 'One of our morning shift cashiers typed the PIN incorrectly 3 times. Can a Super Admin release the security lock and reset the temporary PIN so they can resume lunch shift orders?',
        timestamp: '2026-09-25T07:10:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'TCK-8871',
    subject: 'Zakat & Tax Authority (ETA) e-Invoice QR Code Compliance Check',
    category: 'billing',
    priority: 'low',
    status: 'resolved',
    businessId: 'biz_105',
    businessName: 'Nile Fresh Groceries',
    businessPlan: 'Enterprise',
    customerContact: {
      name: 'Kareem Fahmy',
      email: 'kareem@nilefresh.com',
      role: 'Finance Director',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=120&h=120&q=80',
    },
    assignedTo: SUPPORT_ADMIN_STAFF[2], // Alex Morgan
    createdAt: '2026-09-24T14:00:00Z',
    updatedAt: '2026-09-24T16:30:00Z',
    slaTargetAt: '2026-09-25T14:00:00Z',
    isSlaBreached: false,
    tags: ['ETA Compliance', 'B2B Invoices', 'QR Code'],
    attachments: [
      {
        id: 'att_04',
        name: 'sample_zatca_tax_invoice.pdf',
        size: '312 KB',
        type: 'pdf',
        url: '#',
        uploadedAt: '2026-09-24T14:00:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_09',
        sender: {
          id: 'usr_kareem',
          name: 'Kareem Fahmy',
          email: 'kareem@nilefresh.com',
          role: 'Finance Director',
          avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: false,
        },
        body: 'We need confirmation if the Base64 QR code printed on our POS receipts meets the latest Egyptian Tax Authority cryptographic hash requirement for B2B transactions.',
        timestamp: '2026-09-24T14:00:00Z',
        isInternal: false,
      },
      {
        id: 'msg_10',
        sender: {
          id: 'adm_alex',
          name: 'Alex Morgan',
          email: 'superadmin@mot7km.com',
          role: 'Global Platform Admin',
          avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'Hello Kareem. Yes, Mot7km ERP uses TLV (Tag-Length-Value) standard encoding with SHA-256 digital signature embedded into every tax invoice. All receipts pass the official ETA validator portal without exception.',
        timestamp: '2026-09-24T16:30:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'TCK-8860',
    subject: 'Inventory CSV bulk ingredient import parsing failure with special characters',
    category: 'technical',
    priority: 'high',
    status: 'pending',
    businessId: 'biz_132',
    businessName: 'Cairo Tech Cafe',
    businessPlan: 'Pro',
    customerContact: {
      name: 'Youssef El-Shamy',
      email: 'youssef@cairotechcafe.com',
      role: 'Operations Head',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=120&h=120&q=80',
    },
    assignedTo: SUPPORT_ADMIN_STAFF[1], // Sarah Karim
    createdAt: '2026-09-24T18:20:00Z',
    updatedAt: '2026-09-25T01:10:00Z',
    slaTargetAt: '2026-09-25T02:20:00Z',
    isSlaBreached: true,
    tags: ['CSV Import', 'UTF-8', 'Recipes'],
    attachments: [
      {
        id: 'att_05',
        name: 'raw_ingredients_batch_sep2026.csv',
        size: '89 KB',
        type: 'file',
        url: '#',
        uploadedAt: '2026-09-24T18:20:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_11',
        sender: {
          id: 'usr_youssef',
          name: 'Youssef El-Shamy',
          email: 'youssef@cairotechcafe.com',
          role: 'Operations Head',
          avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: false,
        },
        body: 'When uploading our ingredients master catalog containing Arabic diacritics and quotes, the importer aborts at row 142 with "Invalid encoding format". File is attached.',
        timestamp: '2026-09-24T18:20:00Z',
        isInternal: false,
      },
      {
        id: 'msg_12',
        sender: {
          id: 'adm_sarah',
          name: 'Sarah Karim',
          email: 'sarah.k@mot7km.com',
          role: 'Senior ERP Solutions Engineer',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'INTERNAL NOTE: The CSV was exported from Windows Excel in CP1256 encoding instead of UTF-8 with BOM. Applied auto-charset sniffing on the backend parser.',
        timestamp: '2026-09-25T01:05:00Z',
        isInternal: true,
      },
      {
        id: 'msg_13',
        sender: {
          id: 'adm_sarah',
          name: 'Sarah Karim',
          email: 'sarah.k@mot7km.com',
          role: 'Senior ERP Solutions Engineer',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'Hello Youssef! We deployed an encoding patch to support Windows Arabic Excel CSVs. Please try re-uploading your file directly from the Inventory tab.',
        timestamp: '2026-09-25T01:10:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 'TCK-8852',
    subject: 'Requesting webhook integration for third-party courier dispatch API',
    category: 'feature_request',
    priority: 'low',
    status: 'closed',
    businessId: 'biz_140',
    businessName: 'Express Burger Chain',
    businessPlan: 'Enterprise',
    customerContact: {
      name: 'Rami Mansour',
      email: 'rami@expressburger.com',
      role: 'CTO',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80',
    },
    assignedTo: SUPPORT_ADMIN_STAFF[2], // Alex Morgan
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-24T10:15:00Z',
    slaTargetAt: '2026-09-24T11:00:00Z',
    isSlaBreached: false,
    tags: ['Webhooks', 'Delivery API', 'Closed'],
    attachments: [],
    messages: [
      {
        id: 'msg_14',
        sender: {
          id: 'usr_rami',
          name: 'Rami Mansour',
          email: 'rami@expressburger.com',
          role: 'CTO',
          avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: false,
        },
        body: 'Does Mot7km have an outgoing webhook event for "order.ready_for_pickup" that our custom delivery dispatch bot can subscribe to?',
        timestamp: '2026-09-23T11:00:00Z',
        isInternal: false,
      },
      {
        id: 'msg_15',
        sender: {
          id: 'adm_alex',
          name: 'Alex Morgan',
          email: 'superadmin@mot7km.com',
          role: 'Global Platform Admin',
          avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&h=120&q=80',
          isStaff: true,
        },
        body: 'Yes! You can configure your endpoint under System Settings > Integrations > Outbound Webhooks, and select "Kitchen Order Status Changes". Documentation link has been shared via developer portal.',
        timestamp: '2026-09-24T10:15:00Z',
        isInternal: false,
      },
    ],
  },
];
