import type {
  KpiMetricItem,
  PulsePoint,
  PlatformHealthItem,
  FunnelStep,
  BusinessStatusDistribution,
  BusinessGrowthMonth,
  PlatformActivitySummary,
  MultiBranchStats,
  GovernorateStat,
} from './analytics.types';

export const INITIAL_OVERVIEW_KPIS: KpiMetricItem[] = [
  {
    key: 'totalBusinesses',
    labelKey: 'analytics.kpi.totalBusinesses',
    current: 1248,
    previous: 1162,
    percentChange: 7.4,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [1020, 1060, 1105, 1140, 1190, 1248],
    accentColor: 'indigo',
    descriptionKey: 'analytics.kpiDesc.totalBusinesses',
  },
  {
    key: 'activeBusinesses',
    labelKey: 'analytics.kpi.activeBusinesses',
    current: 934,
    previous: 865,
    percentChange: 8.0,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [740, 780, 820, 850, 890, 934],
    accentColor: 'emerald',
    descriptionKey: 'analytics.kpiDesc.activeBusinesses',
  },
  {
    key: 'newBusinesses',
    labelKey: 'analytics.kpi.newBusinesses',
    current: 86,
    previous: 72,
    percentChange: 19.4,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [58, 64, 70, 75, 72, 86],
    accentColor: 'teal',
    descriptionKey: 'analytics.kpiDesc.newBusinesses',
  },
  {
    key: 'mrr',
    labelKey: 'analytics.kpi.mrr',
    current: 184500,
    previous: 164150,
    percentChange: 12.4,
    trend: 'up',
    isPositive: true,
    format: 'currency',
    currencyCode: 'EGP',
    sparkline: [80000, 93000, 110000, 128000, 151000, 184500],
    accentColor: 'emerald',
    descriptionKey: 'analytics.kpiDesc.mrr',
  },
  {
    key: 'arr',
    labelKey: 'analytics.kpi.arr',
    current: 2214000,
    previous: 1969800,
    percentChange: 12.2,
    trend: 'up',
    isPositive: true,
    format: 'currency',
    currencyCode: 'EGP',
    sparkline: [960000, 1116000, 1320000, 1536000, 1812000, 2214000],
    accentColor: 'violet',
    descriptionKey: 'analytics.kpiDesc.arr',
  },
  {
    key: 'activeUsers',
    labelKey: 'analytics.kpi.activeUsers',
    current: 7842,
    previous: 7120,
    percentChange: 10.1,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [5800, 6200, 6650, 7050, 7420, 7842],
    accentColor: 'blue',
    descriptionKey: 'analytics.kpiDesc.activeUsers',
  },
  {
    key: 'orders',
    labelKey: 'analytics.kpi.orders',
    current: 42391,
    previous: 38150,
    percentChange: 11.1,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [29000, 31500, 34200, 36800, 39500, 42391],
    accentColor: 'amber',
    descriptionKey: 'analytics.kpiDesc.orders',
  },
  {
    key: 'churnRate',
    labelKey: 'analytics.kpi.churnRate',
    current: 2.8,
    previous: 3.2,
    percentChange: 12.5,
    trend: 'down',
    isPositive: true, // Churn going down is POSITIVE
    format: 'percent',
    sparkline: [4.1, 3.6, 3.2, 2.9, 2.8, 2.8],
    accentColor: 'rose',
    descriptionKey: 'analytics.kpiDesc.churnRate',
  },
  {
    key: 'trialToPaid',
    labelKey: 'analytics.kpi.trialToPaid',
    current: 24.6,
    previous: 21.8,
    percentChange: 12.8,
    trend: 'up',
    isPositive: true,
    format: 'percent',
    sparkline: [18.2, 19.5, 20.8, 22.1, 23.4, 24.6],
    accentColor: 'emerald',
    descriptionKey: 'analytics.kpiDesc.trialToPaid',
  },
];

export const PULSE_CHART_MONTHLY: PulsePoint[] = [
  {
    id: 'm1',
    labelEn: 'Jan',
    labelAr: 'يناير',
    mrr: 80000,
    mrrPrev: 68000,
    activeBusinesses: 620,
    newBusinesses: 45,
  },
  {
    id: 'm2',
    labelEn: 'Feb',
    labelAr: 'فبراير',
    mrr: 93000,
    mrrPrev: 75000,
    activeBusinesses: 690,
    newBusinesses: 52,
  },
  {
    id: 'm3',
    labelEn: 'Mar',
    labelAr: 'مارس',
    mrr: 110000,
    mrrPrev: 84000,
    activeBusinesses: 760,
    newBusinesses: 61,
  },
  {
    id: 'm4',
    labelEn: 'Apr',
    labelAr: 'أبريل',
    mrr: 128000,
    mrrPrev: 96000,
    activeBusinesses: 825,
    newBusinesses: 68,
  },
  {
    id: 'm5',
    labelEn: 'May',
    labelAr: 'مايو',
    mrr: 151000,
    mrrPrev: 112000,
    activeBusinesses: 880,
    newBusinesses: 74,
  },
  {
    id: 'm6',
    labelEn: 'Jun',
    labelAr: 'يونيو',
    mrr: 184500,
    mrrPrev: 135000,
    activeBusinesses: 934,
    newBusinesses: 86,
  },
];

export const PULSE_CHART_WEEKLY: PulsePoint[] = [
  {
    id: 'w1',
    labelEn: 'Week 1',
    labelAr: 'الأسبوع 1',
    mrr: 168000,
    mrrPrev: 152000,
    activeBusinesses: 902,
    newBusinesses: 18,
  },
  {
    id: 'w2',
    labelEn: 'Week 2',
    labelAr: 'الأسبوع 2',
    mrr: 172500,
    mrrPrev: 155000,
    activeBusinesses: 911,
    newBusinesses: 21,
  },
  {
    id: 'w3',
    labelEn: 'Week 3',
    labelAr: 'الأسبوع 3',
    mrr: 176200,
    mrrPrev: 158500,
    activeBusinesses: 920,
    newBusinesses: 22,
  },
  {
    id: 'w4',
    labelEn: 'Week 4',
    labelAr: 'الأسبوع 4',
    mrr: 180400,
    mrrPrev: 161000,
    activeBusinesses: 928,
    newBusinesses: 24,
  },
  {
    id: 'w5',
    labelEn: 'Week 5',
    labelAr: 'الأسبوع 5',
    mrr: 182900,
    mrrPrev: 163000,
    activeBusinesses: 931,
    newBusinesses: 20,
  },
  {
    id: 'w6',
    labelEn: 'Week 6 (Current)',
    labelAr: 'الأسبوع 6 (الحالي)',
    mrr: 184500,
    mrrPrev: 164150,
    activeBusinesses: 934,
    newBusinesses: 26,
  },
];

export const PLATFORM_HEALTH_SUBSYSTEMS: PlatformHealthItem[] = [
  {
    id: 'hlth-api',
    nameKey: 'analytics.healthSubsystems.api',
    status: 'healthy',
    metric: '99.98% SLA',
    latencyMs: 28,
  },
  {
    id: 'hlth-db',
    nameKey: 'analytics.healthSubsystems.database',
    status: 'healthy',
    metric: '48 / 200 Conns',
    latencyMs: 14,
  },
  {
    id: 'hlth-storage',
    nameKey: 'analytics.healthSubsystems.storage',
    status: 'healthy',
    metric: '11.8 TB / 15 TB',
    latencyMs: 22,
  },
  {
    id: 'hlth-payments',
    nameKey: 'analytics.healthSubsystems.payments',
    status: 'healthy',
    metric: '99.92% Uptime',
    latencyMs: 38,
  },
  {
    id: 'hlth-notifications',
    nameKey: 'analytics.healthSubsystems.notifications',
    status: 'degraded',
    metric: 'SMS Queue Elevated',
    latencyMs: 82,
  },
];

export const ACTIVATION_FUNNEL_STEPS: FunnelStep[] = [
  {
    id: 'f-signup',
    stepNumber: 1,
    labelKey: 'analytics.funnel.signup',
    count: 1248,
    percentage: 100.0,
  },
  {
    id: 'f-created',
    stepNumber: 2,
    labelKey: 'analytics.funnel.createdBusiness',
    count: 1180,
    percentage: 94.5,
    dropoffPercent: 5.5,
  },
  {
    id: 'f-branch',
    stepNumber: 3,
    labelKey: 'analytics.funnel.addedBranch',
    count: 1090,
    percentage: 87.3,
    dropoffPercent: 7.6,
  },
  {
    id: 'f-products',
    stepNumber: 4,
    labelKey: 'analytics.funnel.addedProducts',
    count: 975,
    percentage: 78.1,
    dropoffPercent: 10.5,
  },
  {
    id: 'f-employee',
    stepNumber: 5,
    labelKey: 'analytics.funnel.addedEmployee',
    count: 890,
    percentage: 71.3,
    dropoffPercent: 8.7,
  },
  {
    id: 'f-tx',
    stepNumber: 6,
    labelKey: 'analytics.funnel.firstTransaction',
    count: 848,
    percentage: 68.0,
    dropoffPercent: 4.7,
  },
];

export const BUSINESS_STATUS_DISTRIBUTION: BusinessStatusDistribution = {
  active: 934,
  trial: 182,
  expired: 67,
  suspended: 41,
  cancelled: 24,
  total: 1248,
};

export const BUSINESS_GROWTH_MONTHS: BusinessGrowthMonth[] = [
  {
    monthKey: 'jan',
    labelEn: 'Jan',
    labelAr: 'يناير',
    newCount: 45,
    activatedCount: 31,
    suspendedCount: 6,
    reactivatedCount: 2,
  },
  {
    monthKey: 'feb',
    labelEn: 'Feb',
    labelAr: 'فبراير',
    newCount: 52,
    activatedCount: 38,
    suspendedCount: 5,
    reactivatedCount: 4,
  },
  {
    monthKey: 'mar',
    labelEn: 'Mar',
    labelAr: 'مارس',
    newCount: 61,
    activatedCount: 44,
    suspendedCount: 8,
    reactivatedCount: 3,
  },
  {
    monthKey: 'apr',
    labelEn: 'Apr',
    labelAr: 'أبريل',
    newCount: 68,
    activatedCount: 49,
    suspendedCount: 7,
    reactivatedCount: 5,
  },
  {
    monthKey: 'may',
    labelEn: 'May',
    labelAr: 'مايو',
    newCount: 74,
    activatedCount: 52,
    suspendedCount: 9,
    reactivatedCount: 6,
  },
  {
    monthKey: 'jun',
    labelEn: 'Jun',
    labelAr: 'يونيو',
    newCount: 86,
    activatedCount: 58,
    suspendedCount: 6,
    reactivatedCount: 8,
  },
];

export const PLATFORM_ACTIVITY_DATA: PlatformActivitySummary = {
  totalOrders: 42391,
  productsAdded: 18420,
  employeesAdded: 4810,
  branchesCreated: 1203,
};

export const MULTI_BRANCH_STATS: MultiBranchStats = {
  totalBranches: 1823,
  activeBranches: 1690,
  avgBranchesPerBusiness: 1.8,
  avgOrdersPerBranchDay: 25.1,
  avgSalesPerBranchDay: 2840,
  avgEmployeesPerBranch: 2.8,
};

export const EGYPT_GOVERNORATES_DATA: GovernorateStat[] = [
  {
    id: 'gov-cairo',
    nameEn: 'Cairo',
    nameAr: 'القاهرة',
    businessCount: 524,
    percent: 42.0,
  },
  {
    id: 'gov-giza',
    nameEn: 'Giza',
    nameAr: 'الجيزة',
    businessCount: 286,
    percent: 22.9,
  },
  {
    id: 'gov-alex',
    nameEn: 'Alexandria',
    nameAr: 'الإسكندرية',
    businessCount: 198,
    percent: 15.9,
  },
  {
    id: 'gov-ismailia',
    nameEn: 'Ismailia & Canal Cities',
    nameAr: 'الإسماعيلية ومدن القناة',
    businessCount: 96,
    percent: 7.7,
  },
  {
    id: 'gov-dakahlia',
    nameEn: 'Dakahlia (Mansoura)',
    nameAr: 'الدقهلية (المنصورة)',
    businessCount: 74,
    percent: 5.9,
  },
  {
    id: 'gov-others',
    nameEn: 'Other Governorates',
    nameAr: 'باقي المحافظات',
    businessCount: 70,
    percent: 5.6,
  },
];
