import type {
  KpiMetricItem,
  PulsePoint,
  PlatformHealthItem,
  FunnelStep,
  BusinessStatusDistribution,
  BusinessGrowthMonth,
  PlatformActivitySummary,
  MultiBranchStats,
  GovernorateStat,
  MrrMovementSummary,
  SubscriptionPlanBreakdown,
  BillingCycleStat,
  SubscriptionCadenceStats,
  PaymentGatewayStat,
  PaymentFailureReasonItem,
  InvoiceCollectionStats,
  TrialConversionStep,
  TrialStatusOverview,
  CohortMonthItem,
  RetentionCurvePoint,
  TrialDropoffReason,
  UserActivitySummary,
  UserRoleItem,
  UserEngagementSegment,
  ProductFeatureUsageItem,
  FeatureAdoptionFunnelStep,
  GmvIntelligenceSummary,
  ApiPerformanceSummary,
  ApiEndpointMetric,
  SystemErrorCategory,
  SupportOperationsStats,
  NotificationChannelTelemetry,
  AdminAuditActivitySummary,
} from './analytics.types';

export const INITIAL_OVERVIEW_KPIS: KpiMetricItem[] = [
  {
    key: 'totalBusinesses',
    labelKey: 'analytics.kpi.totalBusinesses',
    current: 1248,
    previous: 1162,
    percentChange: 7.4,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [1020, 1060, 1105, 1140, 1190, 1248],
    accentColor: 'indigo',
    descriptionKey: 'analytics.kpiDesc.totalBusinesses',
  },
  {
    key: 'activeBusinesses',
    labelKey: 'analytics.kpi.activeBusinesses',
    current: 934,
    previous: 865,
    percentChange: 8.0,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [740, 780, 820, 850, 890, 934],
    accentColor: 'emerald',
    descriptionKey: 'analytics.kpiDesc.activeBusinesses',
  },
  {
    key: 'newBusinesses',
    labelKey: 'analytics.kpi.newBusinesses',
    current: 86,
    previous: 72,
    percentChange: 19.4,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [58, 64, 70, 75, 72, 86],
    accentColor: 'teal',
    descriptionKey: 'analytics.kpiDesc.newBusinesses',
  },
  {
    key: 'mrr',
    labelKey: 'analytics.kpi.mrr',
    current: 184500,
    previous: 164150,
    percentChange: 12.4,
    trend: 'up',
    isPositive: true,
    format: 'currency',
    currencyCode: 'EGP',
    sparkline: [80000, 93000, 110000, 128000, 151000, 184500],
    accentColor: 'emerald',
    descriptionKey: 'analytics.kpiDesc.mrr',
  },
  {
    key: 'arr',
    labelKey: 'analytics.kpi.arr',
    current: 2214000,
    previous: 1969800,
    percentChange: 12.2,
    trend: 'up',
    isPositive: true,
    format: 'currency',
    currencyCode: 'EGP',
    sparkline: [960000, 1116000, 1320000, 1536000, 1812000, 2214000],
    accentColor: 'violet',
    descriptionKey: 'analytics.kpiDesc.arr',
  },
  {
    key: 'activeUsers',
    labelKey: 'analytics.kpi.activeUsers',
    current: 7842,
    previous: 7120,
    percentChange: 10.1,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [5800, 6200, 6650, 7050, 7420, 7842],
    accentColor: 'blue',
    descriptionKey: 'analytics.kpiDesc.activeUsers',
  },
  {
    key: 'orders',
    labelKey: 'analytics.kpi.orders',
    current: 42391,
    previous: 38150,
    percentChange: 11.1,
    trend: 'up',
    isPositive: true,
    format: 'number',
    sparkline: [29000, 31500, 34200, 36800, 39500, 42391],
    accentColor: 'amber',
    descriptionKey: 'analytics.kpiDesc.orders',
  },
  {
    key: 'churnRate',
    labelKey: 'analytics.kpi.churnRate',
    current: 2.8,
    previous: 3.2,
    percentChange: 12.5,
    trend: 'down',
    isPositive: true, // Churn going down is POSITIVE
    format: 'percent',
    sparkline: [4.1, 3.6, 3.2, 2.9, 2.8, 2.8],
    accentColor: 'rose',
    descriptionKey: 'analytics.kpiDesc.churnRate',
  },
  {
    key: 'trialToPaid',
    labelKey: 'analytics.kpi.trialToPaid',
    current: 24.6,
    previous: 21.8,
    percentChange: 12.8,
    trend: 'up',
    isPositive: true,
    format: 'percent',
    sparkline: [18.2, 19.5, 20.8, 22.1, 23.4, 24.6],
    accentColor: 'emerald',
    descriptionKey: 'analytics.kpiDesc.trialToPaid',
  },
];

export const PULSE_CHART_MONTHLY: PulsePoint[] = [
  {
    id: 'm1',
    labelEn: 'Jan',
    labelAr: 'يناير',
    mrr: 80000,
    mrrPrev: 68000,
    activeBusinesses: 620,
    newBusinesses: 45,
  },
  {
    id: 'm2',
    labelEn: 'Feb',
    labelAr: 'فبراير',
    mrr: 93000,
    mrrPrev: 75000,
    activeBusinesses: 690,
    newBusinesses: 52,
  },
  {
    id: 'm3',
    labelEn: 'Mar',
    labelAr: 'مارس',
    mrr: 110000,
    mrrPrev: 84000,
    activeBusinesses: 760,
    newBusinesses: 61,
  },
  {
    id: 'm4',
    labelEn: 'Apr',
    labelAr: 'أبريل',
    mrr: 128000,
    mrrPrev: 96000,
    activeBusinesses: 825,
    newBusinesses: 68,
  },
  {
    id: 'm5',
    labelEn: 'May',
    labelAr: 'مايو',
    mrr: 151000,
    mrrPrev: 112000,
    activeBusinesses: 880,
    newBusinesses: 74,
  },
  {
    id: 'm6',
    labelEn: 'Jun',
    labelAr: 'يونيو',
    mrr: 184500,
    mrrPrev: 135000,
    activeBusinesses: 934,
    newBusinesses: 86,
  },
];

export const PULSE_CHART_WEEKLY: PulsePoint[] = [
  {
    id: 'w1',
    labelEn: 'Week 1',
    labelAr: 'الأسبوع 1',
    mrr: 168000,
    mrrPrev: 152000,
    activeBusinesses: 902,
    newBusinesses: 18,
  },
  {
    id: 'w2',
    labelEn: 'Week 2',
    labelAr: 'الأسبوع 2',
    mrr: 172500,
    mrrPrev: 155000,
    activeBusinesses: 911,
    newBusinesses: 21,
  },
  {
    id: 'w3',
    labelEn: 'Week 3',
    labelAr: 'الأسبوع 3',
    mrr: 176200,
    mrrPrev: 158500,
    activeBusinesses: 920,
    newBusinesses: 22,
  },
  {
    id: 'w4',
    labelEn: 'Week 4',
    labelAr: 'الأسبوع 4',
    mrr: 180400,
    mrrPrev: 161000,
    activeBusinesses: 928,
    newBusinesses: 24,
  },
  {
    id: 'w5',
    labelEn: 'Week 5',
    labelAr: 'الأسبوع 5',
    mrr: 182900,
    mrrPrev: 163000,
    activeBusinesses: 931,
    newBusinesses: 20,
  },
  {
    id: 'w6',
    labelEn: 'Week 6 (Current)',
    labelAr: 'الأسبوع 6 (الحالي)',
    mrr: 184500,
    mrrPrev: 164150,
    activeBusinesses: 934,
    newBusinesses: 26,
  },
];

export const PLATFORM_HEALTH_SUBSYSTEMS: PlatformHealthItem[] = [
  {
    id: 'hlth-api',
    nameKey: 'analytics.healthSubsystems.api',
    status: 'healthy',
    metric: '99.98% SLA',
    latencyMs: 28,
  },
  {
    id: 'hlth-db',
    nameKey: 'analytics.healthSubsystems.database',
    status: 'healthy',
    metric: '48 / 200 Conns',
    latencyMs: 14,
  },
  {
    id: 'hlth-storage',
    nameKey: 'analytics.healthSubsystems.storage',
    status: 'healthy',
    metric: '11.8 TB / 15 TB',
    latencyMs: 22,
  },
  {
    id: 'hlth-payments',
    nameKey: 'analytics.healthSubsystems.payments',
    status: 'healthy',
    metric: '99.92% Uptime',
    latencyMs: 38,
  },
  {
    id: 'hlth-notifications',
    nameKey: 'analytics.healthSubsystems.notifications',
    status: 'degraded',
    metric: 'SMS Queue Elevated',
    latencyMs: 82,
  },
];

export const ACTIVATION_FUNNEL_STEPS: FunnelStep[] = [
  {
    id: 'f-signup',
    stepNumber: 1,
    labelKey: 'analytics.funnel.signup',
    count: 1248,
    percentage: 100.0,
  },
  {
    id: 'f-created',
    stepNumber: 2,
    labelKey: 'analytics.funnel.createdBusiness',
    count: 1180,
    percentage: 94.5,
    dropoffPercent: 5.5,
  },
  {
    id: 'f-branch',
    stepNumber: 3,
    labelKey: 'analytics.funnel.addedBranch',
    count: 1090,
    percentage: 87.3,
    dropoffPercent: 7.6,
  },
  {
    id: 'f-products',
    stepNumber: 4,
    labelKey: 'analytics.funnel.addedProducts',
    count: 975,
    percentage: 78.1,
    dropoffPercent: 10.5,
  },
  {
    id: 'f-employee',
    stepNumber: 5,
    labelKey: 'analytics.funnel.addedEmployee',
    count: 890,
    percentage: 71.3,
    dropoffPercent: 8.7,
  },
  {
    id: 'f-tx',
    stepNumber: 6,
    labelKey: 'analytics.funnel.firstTransaction',
    count: 848,
    percentage: 68.0,
    dropoffPercent: 4.7,
  },
];

export const BUSINESS_STATUS_DISTRIBUTION: BusinessStatusDistribution = {
  active: 934,
  trial: 182,
  expired: 67,
  suspended: 41,
  cancelled: 24,
  total: 1248,
};

export const BUSINESS_GROWTH_MONTHS: BusinessGrowthMonth[] = [
  {
    monthKey: 'jan',
    labelEn: 'Jan',
    labelAr: 'يناير',
    newCount: 45,
    activatedCount: 31,
    suspendedCount: 6,
    reactivatedCount: 2,
  },
  {
    monthKey: 'feb',
    labelEn: 'Feb',
    labelAr: 'فبراير',
    newCount: 52,
    activatedCount: 38,
    suspendedCount: 5,
    reactivatedCount: 4,
  },
  {
    monthKey: 'mar',
    labelEn: 'Mar',
    labelAr: 'مارس',
    newCount: 61,
    activatedCount: 44,
    suspendedCount: 8,
    reactivatedCount: 3,
  },
  {
    monthKey: 'apr',
    labelEn: 'Apr',
    labelAr: 'أبريل',
    newCount: 68,
    activatedCount: 49,
    suspendedCount: 7,
    reactivatedCount: 5,
  },
  {
    monthKey: 'may',
    labelEn: 'May',
    labelAr: 'مايو',
    newCount: 74,
    activatedCount: 52,
    suspendedCount: 9,
    reactivatedCount: 6,
  },
  {
    monthKey: 'jun',
    labelEn: 'Jun',
    labelAr: 'يونيو',
    newCount: 86,
    activatedCount: 58,
    suspendedCount: 6,
    reactivatedCount: 8,
  },
];

export const PLATFORM_ACTIVITY_DATA: PlatformActivitySummary = {
  totalOrders: 42391,
  productsAdded: 18420,
  employeesAdded: 4810,
  branchesCreated: 1203,
};

export const MULTI_BRANCH_STATS: MultiBranchStats = {
  totalBranches: 1823,
  activeBranches: 1690,
  avgBranchesPerBusiness: 1.8,
  avgOrdersPerBranchDay: 25.1,
  avgSalesPerBranchDay: 2840,
  avgEmployeesPerBranch: 2.8,
};

export const EGYPT_GOVERNORATES_DATA: GovernorateStat[] = [
  {
    id: 'gov-cairo',
    nameEn: 'Cairo',
    nameAr: 'القاهرة',
    businessCount: 524,
    percent: 42.0,
  },
  {
    id: 'gov-giza',
    nameEn: 'Giza',
    nameAr: 'الجيزة',
    businessCount: 286,
    percent: 22.9,
  },
  {
    id: 'gov-alex',
    nameEn: 'Alexandria',
    nameAr: 'الإسكندرية',
    businessCount: 198,
    percent: 15.9,
  },
  {
    id: 'gov-ismailia',
    nameEn: 'Ismailia & Canal Cities',
    nameAr: 'الإسماعيلية ومدن القناة',
    businessCount: 96,
    percent: 7.7,
  },
  {
    id: 'gov-dakahlia',
    nameEn: 'Dakahlia (Mansoura)',
    nameAr: 'الدقهلية (المنصورة)',
    businessCount: 74,
    percent: 5.9,
  },
  {
    id: 'gov-others',
    nameEn: 'Other Governorates',
    nameAr: 'باقي المحافظات',
    businessCount: 70,
    percent: 5.6,
  },
];

// -------------------------------------------------------------
// Phase 3: Subscriptions, Revenue & Payment Intelligence Datasets
// -------------------------------------------------------------

export const MRR_MOVEMENT_SUMMARY: MrrMovementSummary = {
  startingMrr: 164150,
  newMrr: 18200,
  expansionMrr: 9450,
  contractionMrr: 2800,
  churnedMrr: 4500,
  endingMrr: 184500,
  netNewMrr: 20350,
  quickRatio: 3.8,
  steps: [
    {
      key: 'starting',
      labelKey: 'analytics.revenue.startingMrr',
      amount: 164150,
      isTotal: true,
    },
    {
      key: 'new',
      labelKey: 'analytics.revenue.newMrr',
      amount: 18200,
      isPositive: true,
    },
    {
      key: 'expansion',
      labelKey: 'analytics.revenue.expansionMrr',
      amount: 9450,
      isPositive: true,
    },
    {
      key: 'contraction',
      labelKey: 'analytics.revenue.contractionMrr',
      amount: -2800,
      isNegative: true,
    },
    {
      key: 'churn',
      labelKey: 'analytics.revenue.churnedMrr',
      amount: -4500,
      isNegative: true,
    },
    {
      key: 'ending',
      labelKey: 'analytics.revenue.endingMrr',
      amount: 184500,
      isTotal: true,
    },
  ],
};

export const SUBSCRIPTION_PLANS_DATA: SubscriptionPlanBreakdown[] = [
  {
    id: 'plan-basic',
    nameKey: 'analytics.plans.basic',
    tier: 'basic',
    subscribersCount: 271,
    percent: 29.0,
    mrrAmount: 40650,
    mrrPercent: 22.0,
    priceMonthly: 150,
    color: 'bg-emerald-500',
  },
  {
    id: 'plan-pro',
    nameKey: 'analytics.plans.pro',
    tier: 'pro',
    subscribersCount: 486,
    percent: 52.0,
    mrrAmount: 97200,
    mrrPercent: 52.7,
    priceMonthly: 200,
    color: 'bg-primary',
  },
  {
    id: 'plan-enterprise',
    nameKey: 'analytics.plans.enterprise',
    tier: 'enterprise',
    subscribersCount: 177,
    percent: 19.0,
    mrrAmount: 46650,
    mrrPercent: 25.3,
    priceMonthly: 264,
    color: 'bg-purple-500',
  },
];

export const BILLING_CYCLES_DATA: BillingCycleStat[] = [
  {
    cycle: 'monthly',
    labelKey: 'analytics.plans.monthlyCycle',
    subscribersCount: 635,
    percent: 68.0,
    annualDiscountNote: 'Standard monthly recurring cadence',
  },
  {
    cycle: 'annual',
    labelKey: 'analytics.plans.annualCycle',
    subscribersCount: 299,
    percent: 32.0,
    annualDiscountNote: 'Includes 2 months free (20% discount applied)',
  },
];

export const SUBSCRIPTION_CADENCE_DATA: SubscriptionCadenceStats = {
  monthlyUpgrades: 48,
  monthlyDowngrades: 9,
  autoRenewPercent: 84.5,
  upcomingRenewals7d: 62,
};

export const PAYMENT_GATEWAYS_DATA: PaymentGatewayStat[] = [
  {
    id: 'gw-cards',
    name: 'Credit & Debit Cards',
    methodKey: 'analytics.payments.cards',
    volumeEgp: 1539000,
    txCount: 15200,
    successRate: 95.8,
    sharePercent: 54.0,
    color: 'bg-indigo-500',
  },
  {
    id: 'gw-meeza',
    name: 'Meeza Cards',
    methodKey: 'analytics.payments.meeza',
    volumeEgp: 627000,
    txCount: 7120,
    successRate: 94.2,
    sharePercent: 22.0,
    color: 'bg-emerald-500',
  },
  {
    id: 'gw-wallets',
    name: 'Mobile Wallets & InstaPay',
    methodKey: 'analytics.payments.wallets',
    volumeEgp: 513000,
    txCount: 6430,
    successRate: 97.4,
    sharePercent: 18.0,
    color: 'bg-amber-500',
  },
  {
    id: 'gw-bank',
    name: 'Bank Transfer / Direct Wire',
    methodKey: 'analytics.payments.bankWire',
    volumeEgp: 171000,
    txCount: 480,
    successRate: 99.1,
    sharePercent: 6.0,
    color: 'bg-teal-500',
  },
];

export const PAYMENT_FAILURE_REASONS: PaymentFailureReasonItem[] = [
  {
    id: 'fail-balance',
    labelKey: 'analytics.payments.failBalance',
    count: 523,
    percent: 48.0,
    category: 'balance',
  },
  {
    id: 'fail-expiry',
    labelKey: 'analytics.payments.failExpiry',
    count: 261,
    percent: 24.0,
    category: 'expiry',
  },
  {
    id: 'fail-timeout',
    labelKey: 'analytics.payments.failTimeout',
    count: 196,
    percent: 18.0,
    category: 'network',
  },
  {
    id: 'fail-fraud',
    labelKey: 'analytics.payments.failFraud',
    count: 109,
    percent: 10.0,
    category: 'fraud',
  },
];

export const INVOICE_COLLECTION_DATA: InvoiceCollectionStats = {
  totalInvoicesCount: 1480,
  totalInvoicesAmount: 2850000,
  paidCount: 1392,
  paidAmount: 2681850,
  paidPercent: 94.1,
  pendingCount: 64,
  pendingAmount: 122550,
  pendingPercent: 4.3,
  overdueCount: 24,
  overdueAmount: 45600,
  overduePercent: 1.6,
  dsoDays: 3.2,
  totalRefundedAmount: 12400,
  refundsRate: 0.43,
};

// -------------------------------------------------------------
// Phase 4: Trials & Cohort Retention Intelligence Datasets
// -------------------------------------------------------------

export const TRIAL_STATUS_OVERVIEW: TrialStatusOverview = {
  activeTrials: 182,
  convertedPaid: 246,
  expiredUnconverted: 410,
  extendedTrials: 62,
  avgDaysToConvert: 8.4,
  totalTrials: 1000,
  conversionRate: 24.6,
};

export const TRIAL_CONVERSION_STEPS: TrialConversionStep[] = [
  {
    id: 't-visitors',
    stepNumber: 1,
    labelKey: 'analytics.trials.stepVisitors',
    count: 24500,
    conversionPercent: 100.0,
  },
  {
    id: 't-signups',
    stepNumber: 2,
    labelKey: 'analytics.trials.stepSignups',
    count: 1248,
    conversionPercent: 5.1,
    dropoffPercent: 94.9,
    stageAvgTimeDays: 0.2,
  },
  {
    id: 't-started',
    stepNumber: 3,
    labelKey: 'analytics.trials.stepTrialStarted',
    count: 1000,
    conversionPercent: 80.1,
    dropoffPercent: 19.9,
    stageAvgTimeDays: 0.5,
  },
  {
    id: 't-configured',
    stepNumber: 4,
    labelKey: 'analytics.trials.stepConfigured',
    count: 680,
    conversionPercent: 68.0,
    dropoffPercent: 32.0,
    stageAvgTimeDays: 2.1,
  },
  {
    id: 't-active',
    stepNumber: 5,
    labelKey: 'analytics.trials.stepActiveDay7',
    count: 420,
    conversionPercent: 42.0,
    dropoffPercent: 38.2,
    stageAvgTimeDays: 5.4,
  },
  {
    id: 't-paid',
    stepNumber: 6,
    labelKey: 'analytics.trials.stepPaid',
    count: 246,
    conversionPercent: 24.6,
    dropoffPercent: 41.4,
    stageAvgTimeDays: 8.4,
  },
];

export const COHORT_MONTHS_DATA: CohortMonthItem[] = [
  {
    monthKey: 'jan',
    labelEn: 'Jan 2025',
    labelAr: 'يناير 2025',
    cohortSize: 140,
    retentionPercentages: [100.0, 82.1, 71.4, 65.0, 59.3, 54.3],
  },
  {
    monthKey: 'feb',
    labelEn: 'Feb 2025',
    labelAr: 'فبراير 2025',
    cohortSize: 155,
    retentionPercentages: [100.0, 84.5, 74.2, 68.4, 61.9, null],
  },
  {
    monthKey: 'mar',
    labelEn: 'Mar 2025',
    labelAr: 'مارس 2025',
    cohortSize: 172,
    retentionPercentages: [100.0, 87.8, 77.3, 71.0, null, null],
  },
  {
    monthKey: 'apr',
    labelEn: 'Apr 2025',
    labelAr: 'أبريل 2025',
    cohortSize: 188,
    retentionPercentages: [100.0, 88.8, 79.2, null, null, null],
  },
  {
    monthKey: 'may',
    labelEn: 'May 2025',
    labelAr: 'مايو 2025',
    cohortSize: 204,
    retentionPercentages: [100.0, 91.2, null, null, null, null],
  },
  {
    monthKey: 'jun',
    labelEn: 'Jun 2025',
    labelAr: 'يونيو 2025',
    cohortSize: 218,
    retentionPercentages: [100.0, null, null, null, null, null],
  },
];

export const RETENTION_CURVES_DATA: RetentionCurvePoint[] = [
  {
    monthIndex: 0,
    label: 'Month 0',
    tenantRetention: 100,
    userRetention: 100,
    benchmarkRetention: 100,
  },
  {
    monthIndex: 1,
    label: 'Month 1',
    tenantRetention: 82.4,
    userRetention: 76.2,
    benchmarkRetention: 65.0,
  },
  {
    monthIndex: 2,
    label: 'Month 2',
    tenantRetention: 73.1,
    userRetention: 66.5,
    benchmarkRetention: 54.0,
  },
  {
    monthIndex: 3,
    label: 'Month 3',
    tenantRetention: 65.2,
    userRetention: 58.4,
    benchmarkRetention: 46.0,
  },
  {
    monthIndex: 4,
    label: 'Month 4',
    tenantRetention: 59.8,
    userRetention: 51.0,
    benchmarkRetention: 42.0,
  },
  {
    monthIndex: 5,
    label: 'Month 5',
    tenantRetention: 54.3,
    userRetention: 44.8,
    benchmarkRetention: 38.0,
  },
];

export const TRIAL_DROPOFF_REASONS: TrialDropoffReason[] = [
  {
    id: 'drop-budget',
    reasonKey: 'analytics.trials.reasonBudget',
    count: 140,
    percent: 34.0,
    category: 'budget',
  },
  {
    id: 'drop-hardware',
    reasonKey: 'analytics.trials.reasonHardware',
    count: 115,
    percent: 28.0,
    category: 'hardware',
  },
  {
    id: 'drop-setup',
    reasonKey: 'analytics.trials.reasonSetup',
    count: 74,
    percent: 18.0,
    category: 'setup',
  },
  {
    id: 'drop-training',
    reasonKey: 'analytics.trials.reasonTraining',
    count: 49,
    percent: 12.0,
    category: 'training',
  },
  {
    id: 'drop-alternative',
    reasonKey: 'analytics.trials.reasonAlternative',
    count: 32,
    percent: 8.0,
    category: 'alternative',
  },
];

// -------------------------------------------------------------
// Phase 5: Users, Product Usage & GMV Intelligence Datasets
// -------------------------------------------------------------

export const USER_ACTIVITY_DATA: UserActivitySummary = {
  activeUsers: 7842,
  totalRegisteredUsers: 9250,
  newUsersThisMonth: 540,
  dau: 4210,
  wau: 6850,
  mau: 7842,
  stickinessRatio: 53.7,
};

export const USER_ROLES_DATA: UserRoleItem[] = [
  {
    roleKey: 'cashiers',
    nameKey: 'analytics.users.roleCashiers',
    count: 4414,
    percent: 56.3,
    color: 'bg-emerald-500',
  },
  {
    roleKey: 'managers',
    nameKey: 'analytics.users.roleManagers',
    count: 2180,
    percent: 27.8,
    color: 'bg-primary',
  },
  {
    roleKey: 'owners',
    nameKey: 'analytics.users.roleOwners',
    count: 1248,
    percent: 15.9,
    color: 'bg-purple-500',
  },
];

export const USER_ENGAGEMENT_SEGMENTS: UserEngagementSegment[] = [
  {
    segmentKey: 'power',
    labelKey: 'analytics.users.segPower',
    count: 3294,
    percent: 42.0,
    descriptionKey: 'analytics.users.segPowerDesc',
    color: 'text-emerald-500',
  },
  {
    segmentKey: 'active',
    labelKey: 'analytics.users.segActive',
    count: 2980,
    percent: 38.0,
    descriptionKey: 'analytics.users.segActiveDesc',
    color: 'text-primary',
  },
  {
    segmentKey: 'occasional',
    labelKey: 'analytics.users.segOccasional',
    count: 1098,
    percent: 14.0,
    descriptionKey: 'analytics.users.segOccasionalDesc',
    color: 'text-amber-500',
  },
  {
    segmentKey: 'dormant',
    labelKey: 'analytics.users.segDormant',
    count: 470,
    percent: 6.0,
    descriptionKey: 'analytics.users.segDormantDesc',
    color: 'text-rose-500',
  },
];

export const PRODUCT_FEATURE_USAGE_DATA: ProductFeatureUsageItem[] = [
  {
    id: 'feat-menu',
    featureKey: 'menu',
    nameKey: 'analytics.features.menu',
    adoptionCount: 920,
    adoptionPercent: 98.5,
    dailyInteractions: 18420,
    trend: '+14% MoM',
    color: 'bg-indigo-500',
  },
  {
    id: 'feat-pos',
    featureKey: 'pos',
    nameKey: 'analytics.features.pos',
    adoptionCount: 710,
    adoptionPercent: 76.0,
    dailyInteractions: 42391,
    trend: '+19% MoM',
    color: 'bg-emerald-500',
  },
  {
    id: 'feat-inventory',
    featureKey: 'inventory',
    nameKey: 'analytics.features.inventory',
    adoptionCount: 540,
    adoptionPercent: 57.8,
    dailyInteractions: 6420,
    trend: '+22% MoM',
    color: 'bg-amber-500',
  },
  {
    id: 'feat-reports',
    featureKey: 'reports',
    nameKey: 'analytics.features.reports',
    adoptionCount: 420,
    adoptionPercent: 45.0,
    dailyInteractions: 1840,
    trend: '+28% MoM',
    color: 'bg-teal-500',
  },
  {
    id: 'feat-reviews',
    featureKey: 'reviews',
    nameKey: 'analytics.features.reviews',
    adoptionCount: 190,
    adoptionPercent: 20.3,
    dailyInteractions: 480,
    trend: '+35% MoM',
    color: 'bg-rose-500',
  },
];

export const FEATURE_ADOPTION_FUNNEL_STEPS: FeatureAdoptionFunnelStep[] = [
  {
    id: 'fa-eligible',
    stepNumber: 1,
    labelKey: 'analytics.adoption.eligibleMerchants',
    count: 800,
    percentage: 100.0,
  },
  {
    id: 'fa-enabled',
    stepNumber: 2,
    labelKey: 'analytics.adoption.flagEnabled',
    count: 650,
    percentage: 81.3,
    dropoffPercent: 18.7,
  },
  {
    id: 'fa-first-use',
    stepNumber: 3,
    labelKey: 'analytics.adoption.firstInteraction',
    count: 310,
    percentage: 38.8,
    dropoffPercent: 52.3,
  },
  {
    id: 'fa-habitual',
    stepNumber: 4,
    labelKey: 'analytics.adoption.habitualUsage',
    count: 245,
    percentage: 30.6,
    dropoffPercent: 21.0,
  },
];

export const GMV_INTELLIGENCE_DATA: GmvIntelligenceSummary = {
  totalGmv: 4850000,
  totalOrders: 42391,
  aov: 114.4,
  platformRevenue: 210000,
  takeRatePercent: 4.3,
  businessTypeShares: [
    {
      typeKey: 'restaurants',
      nameKey: 'analytics.gmv.typeRestaurants',
      gmvAmount: 2813000,
      percent: 58.0,
      ordersCount: 26400,
      color: 'bg-amber-500',
    },
    {
      typeKey: 'retail',
      nameKey: 'analytics.gmv.typeRetail',
      gmvAmount: 1261000,
      percent: 26.0,
      ordersCount: 10800,
      color: 'bg-emerald-500',
    },
    {
      typeKey: 'services',
      nameKey: 'analytics.gmv.typeServices',
      gmvAmount: 776000,
      percent: 16.0,
      ordersCount: 5191,
      color: 'bg-primary',
    },
  ],
};

// -------------------------------------------------------------
// Phase 6: Operations, System, Support & Audit Telemetry Datasets
// -------------------------------------------------------------

export const API_PERFORMANCE_SUMMARY: ApiPerformanceSummary = {
  totalRequestsMonth: 1840000,
  successRatePercent: 99.2,
  meanLatencyMs: 182,
  p50LatencyMs: 120,
  p95LatencyMs: 340,
  p99LatencyMs: 820,
  errorCountMonth: 14720,
};

export const API_TOP_ENDPOINTS: ApiEndpointMetric[] = [
  {
    id: 'ep-orders',
    endpoint: '/api/v1/orders',
    method: 'POST',
    callsCount: 642000,
    avgLatencyMs: 142,
    errorRatePercent: 0.4,
    status: 'optimal',
  },
  {
    id: 'ep-products',
    endpoint: '/api/v1/products',
    method: 'GET',
    callsCount: 480000,
    avgLatencyMs: 98,
    errorRatePercent: 0.2,
    status: 'optimal',
  },
  {
    id: 'ep-auth',
    endpoint: '/api/v1/auth/login',
    method: 'POST',
    callsCount: 310000,
    avgLatencyMs: 186,
    errorRatePercent: 1.2,
    status: 'optimal',
  },
  {
    id: 'ep-branches',
    endpoint: '/api/v1/branches/sync',
    method: 'POST',
    callsCount: 198000,
    avgLatencyMs: 310,
    errorRatePercent: 2.8,
    status: 'warning',
  },
  {
    id: 'ep-reports',
    endpoint: '/api/v1/reports/export',
    method: 'GET',
    callsCount: 84000,
    avgLatencyMs: 640,
    errorRatePercent: 3.4,
    status: 'warning',
  },
];

export const SYSTEM_ERROR_CATEGORIES: SystemErrorCategory[] = [
  {
    id: 'err-auth',
    categoryKey: 'analytics.errors.catAuth',
    count: 342,
    percent: 26.6,
    httpCode: '401 / 403',
    color: 'bg-rose-500',
  },
  {
    id: 'err-validation',
    categoryKey: 'analytics.errors.catValidation',
    count: 281,
    percent: 21.9,
    httpCode: '400 / 422',
    color: 'bg-amber-500',
  },
  {
    id: 'err-payment',
    categoryKey: 'analytics.errors.catPayment',
    count: 194,
    percent: 15.1,
    httpCode: '504 Timeout',
    color: 'bg-orange-500',
  },
  {
    id: 'err-throttle',
    categoryKey: 'analytics.errors.catThrottle',
    count: 83,
    percent: 6.5,
    httpCode: '429 Throttle',
    color: 'bg-indigo-500',
  },
  {
    id: 'err-database',
    categoryKey: 'analytics.errors.catDatabase',
    count: 48,
    percent: 3.7,
    httpCode: '500 Internal',
    color: 'bg-purple-500',
  },
  {
    id: 'err-other',
    categoryKey: 'analytics.errors.catOther',
    count: 336,
    percent: 26.2,
    httpCode: 'Client 4xx',
    color: 'bg-blue-500',
  },
];

export const SUPPORT_OPERATIONS_DATA: SupportOperationsStats = {
  openTickets: 42,
  resolvedToday: 83,
  avgFirstResponseMinutes: 18,
  avgResolutionHours: 4.2,
  csatScore: 4.8,
  csatPercentage: 96.4,
  totalTicketsMonth: 1480,
};

export const NOTIFICATION_CHANNELS_DATA: NotificationChannelTelemetry[] = [
  {
    id: 'ch-push',
    channelKey: 'push',
    channelNameKey: 'analytics.ops.pushChannel',
    sentCount: 48200,
    deliveryRatePercent: 98.6,
    color: 'bg-primary',
  },
  {
    id: 'ch-sms',
    channelKey: 'sms',
    channelNameKey: 'analytics.ops.smsChannel',
    sentCount: 24100,
    deliveryRatePercent: 94.2,
    color: 'bg-emerald-500',
  },
  {
    id: 'ch-email',
    channelKey: 'email',
    channelNameKey: 'analytics.ops.emailChannel',
    sentCount: 10100,
    deliveryRatePercent: 98.4,
    openRatePercent: 61.2,
    clickRatePercent: 18.5,
    color: 'bg-amber-500',
  },
];

export const ADMIN_AUDIT_SUMMARY: AdminAuditActivitySummary = {
  totalAdminActionsToday: 438,
  businessConfigEdits: 184,
  subscriptionPlanEdits: 92,
  operatorGovernanceEdits: 64,
  securitySessionRevocations: 98,
  securityAnomaliesCount: 0,
};


