import type { AuditLogEntry } from './audit.types';

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  // 1. Admin Ahmed -> Suspended Business #124 (User's primary prompt example)
  {
    id: 'aud_801941',
    timestamp: '2026-09-25T22:32:00Z',
    actor: {
      id: 'usr_adm_ahmed',
      name: 'Admin Ahmed',
      email: 'ahmed.mansour@mot7km.com',
      role: 'Super Admin',
      avatar: 'AA',
    },
    action: 'business_suspended',
    actionLabel: 'Suspended Business Entity',
    category: 'business',
    severity: 'critical',
    status: 'success',
    resource: {
      type: 'business',
      id: 'biz_124',
      name: 'Al-Ahram Hospitality #124',
      businessId: 'biz_124',
      businessName: 'Al-Ahram Hospitality',
    },
    description:
      'Administrative suspension enforced on tenant account due to unpaid subscription renewal notice.',
    diff: [
      {
        field: 'status',
        label: 'Business Status',
        oldValue: 'active',
        newValue: 'suspended',
      },
      {
        field: 'loginAccess',
        label: 'Staff Portal Access',
        oldValue: 'enabled',
        newValue: 'blocked',
      },
    ],
    clientContext: {
      ipAddress: '156.204.18.92',
      location: 'Cairo, Egypt',
      countryCode: 'EG',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) Chrome/124.0.0.0 Safari/537.36',
      browser: 'Chrome 124 on macOS',
      os: 'macOS Sonoma',
      deviceType: 'desktop',
      requestId: 'req_audit_9f81a0b3e',
    },
    hashSignature: 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    httpStatus: 200,
  },

  // 2. Super Admin -> Changed Business Plan (Basic -> Pro) (User's secondary prompt example)
  {
    id: 'aud_801940',
    timestamp: '2026-09-25T09:14:00Z',
    actor: {
      id: 'usr_root_1',
      name: 'Super Admin (Alex Morgan)',
      email: 'superadmin@mot7km.com',
      role: 'Super Admin',
      avatar: 'AM',
    },
    action: 'business_plan_changed',
    actionLabel: 'Upgraded Subscription Tier',
    category: 'billing',
    severity: 'high',
    status: 'success',
    resource: {
      type: 'subscription',
      id: 'sub_102',
      name: 'El-Nile Hypermarket #102',
      businessId: 't-102',
      businessName: 'El-Nile Hypermarket',
    },
    description:
      'Direct SaaS subscription tier transition executed from Basic Starter Tier to Pro Growth Tier.',
    diff: [
      {
        field: 'planTier',
        label: 'Subscription Plan',
        oldValue: 'Basic Starter Tier',
        newValue: 'Pro Growth Tier',
      },
      {
        field: 'monthlyPrice',
        label: 'Recurring MRR',
        oldValue: '4,999 EGP',
        newValue: '14,999 EGP',
      },
      {
        field: 'maxBranches',
        label: 'Branch Quota',
        oldValue: 3,
        newValue: 15,
      },
      {
        field: 'maxEmployees',
        label: 'Staff Seats Limit',
        oldValue: 10,
        newValue: 50,
      },
    ],
    clientContext: {
      ipAddress: '178.80.12.44',
      location: 'Riyadh, Saudi Arabia',
      countryCode: 'SA',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) Chrome/124.0.0.0 Safari/537.36',
      browser: 'Chrome 124 on macOS',
      os: 'macOS Sonoma',
      deviceType: 'desktop',
      requestId: 'req_audit_7a18f9921',
    },
    hashSignature: 'sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    httpStatus: 200,
  },

  // 3. Super Admin -> Issued Refund
  {
    id: 'aud_801939',
    timestamp: '2026-09-25T01:00:00Z',
    actor: {
      id: 'usr_root_1',
      name: 'Super Admin (Alex Morgan)',
      email: 'superadmin@mot7km.com',
      role: 'Super Admin',
      avatar: 'AM',
    },
    action: 'refund_issued',
    actionLabel: 'Dispatched Electronic Refund',
    category: 'billing',
    severity: 'high',
    status: 'success',
    resource: {
      type: 'invoice',
      id: 'txn_9037',
      name: 'Cairo Fashion Hub Transaction #9037',
      businessId: 't-105',
      businessName: 'Cairo Fashion Hub',
    },
    description:
      'Electronic refund of 8,999 EGP approved and dispatched via Paymob Gateway back to customer card.',
    diff: [
      {
        field: 'refundAmount',
        label: 'Refund Amount',
        oldValue: '0 EGP',
        newValue: '8,999 EGP',
      },
      {
        field: 'settlementStatus',
        label: 'Ledger Status',
        oldValue: 'settled',
        newValue: 'refunded',
      },
    ],
    clientContext: {
      ipAddress: '156.204.18.92',
      location: 'Cairo, Egypt',
      countryCode: 'EG',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15',
      browser: 'Safari Mobile 18.1',
      os: 'iOS 18.1',
      deviceType: 'mobile',
      requestId: 'req_audit_3e990184b',
    },
    hashSignature: 'sha256:36a92cc94a9e0fa97da574026b7f4a9c824c3cbabf28fb21f87873263307990a',
    httpStatus: 200,
  },

  // 4. Unauthorized Access Attempt (Blocked 403)
  {
    id: 'aud_801938',
    timestamp: '2026-09-24T23:45:00Z',
    actor: {
      id: 'usr_anon_actor',
      name: 'Unauthenticated Actor',
      email: 'unknown@tor-exit-node.net',
      role: 'External / Threat',
      avatar: 'XX',
    },
    action: 'unauthorized_access_attempt',
    actionLabel: 'Root API Override Blocked',
    category: 'security',
    severity: 'critical',
    status: 'failure',
    resource: {
      type: 'system_core',
      id: 'sys_purge_endpoint',
      name: 'DELETE /api/v1/system/purge',
    },
    description:
      'Attempted unauthorized invocation of system root purge endpoint without signed cryptographic bearer token.',
    clientContext: {
      ipAddress: '185.220.101.5',
      location: 'Frankfurt, Germany (Tor Exit Node)',
      countryCode: 'DE',
      userAgent: 'curl/8.4.0 (Autonomous Botnet Prober)',
      browser: 'cURL Terminal',
      os: 'Linux Kernel',
      deviceType: 'cli',
      requestId: 'req_audit_err_00912f',
    },
    failureReason: '403 Forbidden: Missing Root Key Signature & IP Blacklisted',
    hashSignature: 'sha256:cb2b3c2d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b',
    httpStatus: 403,
  },

  // 5. Admin Ahmed -> Force Logout & Session Revocation
  {
    id: 'aud_801937',
    timestamp: '2026-09-24T18:20:00Z',
    actor: {
      id: 'usr_adm_ahmed',
      name: 'Admin Ahmed',
      email: 'ahmed.mansour@mot7km.com',
      role: 'Super Admin',
      avatar: 'AA',
    },
    action: 'force_logout',
    actionLabel: 'Revoked Active Sessions',
    category: 'identity',
    severity: 'medium',
    status: 'success',
    resource: {
      type: 'user',
      id: 'usr_sup_2',
      name: 'Omar Al-Husseini (Support Staff)',
    },
    description:
      'Security forced logout triggered across all active web, mobile, and POS endpoint tokens for staff identity.',
    diff: [
      {
        field: 'activeSessionsCount',
        label: 'Active Tokens',
        oldValue: 3,
        newValue: 0,
      },
    ],
    clientContext: {
      ipAddress: '156.204.18.92',
      location: 'Cairo, Egypt',
      countryCode: 'EG',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) Chrome/124.0.0.0 Safari/537.36',
      browser: 'Chrome 124 on macOS',
      os: 'macOS Sonoma',
      deviceType: 'desktop',
      requestId: 'req_audit_8819023c',
    },
    hashSignature: 'sha256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    httpStatus: 200,
  },

  // 6. Super Admin -> Quota Limits Override
  {
    id: 'aud_801936',
    timestamp: '2026-09-24T15:10:00Z',
    actor: {
      id: 'usr_root_2',
      name: 'Super Admin (Ziyad Al-Farhan)',
      email: 'z.farhan@mot7km.com',
      role: 'Super Admin',
      avatar: 'ZF',
    },
    action: 'quota_overridden',
    actionLabel: 'Adjusted Resource Quotas',
    category: 'business',
    severity: 'medium',
    status: 'success',
    resource: {
      type: 'business',
      id: 't-106',
      name: 'Zad Organic Markets #106',
      businessId: 't-106',
      businessName: 'Zad Organic Markets',
    },
    description:
      'Granted operational bonus quotas: +5 additional branch slots and +200GB cloud backup storage allowance.',
    diff: [
      {
        field: 'branchQuota',
        label: 'Branches Allocation',
        oldValue: 8,
        newValue: 13,
      },
      {
        field: 'storageGb',
        label: 'Cloud Storage Limit',
        oldValue: '100 GB',
        newValue: '300 GB',
      },
    ],
    clientContext: {
      ipAddress: '188.161.45.10',
      location: 'Jeddah, Saudi Arabia',
      countryCode: 'SA',
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64) Firefox/125.0',
      browser: 'Firefox 125 on Linux',
      os: 'Linux Ubuntu',
      deviceType: 'desktop',
      requestId: 'req_audit_4419082a',
    },
    hashSignature: 'sha256:9f8e7d6c5b4a392817061524334251607f8e7d6c5b4a39281706152433425160',
    httpStatus: 200,
  },

  // 7. Support Staff -> Impersonated Tenant Console
  {
    id: 'aud_801935',
    timestamp: '2026-09-24T12:05:00Z',
    actor: {
      id: 'usr_sup_1',
      name: 'Maya Chen',
      email: 'maya.chen@mot7km.support',
      role: 'Support Staff',
      avatar: 'MC',
    },
    action: 'impersonation_started',
    actionLabel: 'Elevated Tenant Console Access',
    category: 'security',
    severity: 'high',
    status: 'success',
    resource: {
      type: 'business',
      id: 't-103',
      name: 'Apex Logistics & Trade #103',
      businessId: 't-103',
      businessName: 'Apex Logistics & Trade',
    },
    description:
      'Read-only diagnostic console session initiated under tenant scope to resolve POS dispatch sync ticket #8920.',
    clientContext: {
      ipAddress: '194.170.82.14',
      location: 'Dubai, UAE',
      countryCode: 'AE',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/123.0.0.0 Safari/537.36',
      browser: 'Chrome 123 on Windows 11',
      os: 'Windows 11',
      deviceType: 'desktop',
      requestId: 'req_audit_1190284f',
    },
    hashSignature: 'sha256:a1b2c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e',
    httpStatus: 200,
  },

  // 8. Automated Security Sentinel -> Account Locked (Brute Force Protection)
  {
    id: 'aud_801934',
    timestamp: '2026-09-24T08:30:00Z',
    actor: {
      id: 'sys_sentinel',
      name: 'Security Sentinel Bot',
      email: 'sentinel@mot7km.internal',
      role: 'System Bot',
      avatar: 'BOT',
      isSystem: true,
    },
    action: 'account_locked',
    actionLabel: 'Locked Identity Security Access',
    category: 'security',
    severity: 'critical',
    status: 'warning',
    resource: {
      type: 'user',
      id: 'usr_108',
      name: 'Mostafa Kamel (Giza Tech)',
    },
    description:
      'Zero-trust automatic account freeze triggered following 5 sequential failed 3DS authentication tokens from suspicious IP.',
    diff: [
      {
        field: 'status',
        label: 'Account Status',
        oldValue: 'active',
        newValue: 'locked',
      },
    ],
    clientContext: {
      ipAddress: '197.60.22.11',
      location: 'Giza, Egypt',
      countryCode: 'EG',
      userAgent: 'Automated POS Client 3.2.1',
      browser: 'POS Native Gateway',
      os: 'Android POS OS',
      deviceType: 'api_gateway',
      requestId: 'req_audit_sentinel_99',
    },
    hashSignature: 'sha256:b2c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
    httpStatus: 429,
  },

  // 9. System Auto-Cron -> Rotated Gateway Signing Key
  {
    id: 'aud_801933',
    timestamp: '2026-09-23T23:59:00Z',
    actor: {
      id: 'sys_cron',
      name: 'System Auto-Cron',
      email: 'cron@mot7km.internal',
      role: 'System Bot',
      avatar: 'CRON',
      isSystem: true,
    },
    action: 'api_key_rotated',
    actionLabel: 'Rotated Webhook Signing Secret',
    category: 'system',
    severity: 'low',
    status: 'success',
    resource: {
      type: 'gateway',
      id: 'gw_paymob',
      name: 'Paymob Gateway Webhook Connector',
    },
    description:
      'Automated 90-day cryptographic webhook signing secret rollover completed with zero dropped messages.',
    clientContext: {
      ipAddress: '10.0.4.12 (Internal VPC)',
      location: 'Frankfurt Core Cluster',
      countryCode: 'DE',
      userAgent: 'Kubernetes Internal Security Worker',
      browser: 'Internal RPC',
      os: 'Alpine Linux',
      deviceType: 'api_gateway',
      requestId: 'req_audit_cron_rotation_81',
    },
    hashSignature: 'sha256:c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a',
    httpStatus: 200,
  },

  // 10. Admin Ahmed -> Reactivated Business
  {
    id: 'aud_801932',
    timestamp: '2026-09-23T14:15:00Z',
    actor: {
      id: 'usr_adm_ahmed',
      name: 'Admin Ahmed',
      email: 'ahmed.mansour@mot7km.com',
      role: 'Super Admin',
      avatar: 'AA',
    },
    action: 'business_activated',
    actionLabel: 'Restored Business Operations',
    category: 'business',
    severity: 'high',
    status: 'success',
    resource: {
      type: 'business',
      id: 'biz_105',
      name: 'Cairo Fashion Hub #105',
      businessId: 'biz_105',
      businessName: 'Cairo Fashion Hub',
    },
    description:
      'Reinstated tenant operational credentials following verified wire transfer settlement of outstanding balance.',
    diff: [
      {
        field: 'status',
        label: 'Business Status',
        oldValue: 'suspended',
        newValue: 'active',
      },
    ],
    clientContext: {
      ipAddress: '156.204.18.92',
      location: 'Cairo, Egypt',
      countryCode: 'EG',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) Chrome/124.0.0.0 Safari/537.36',
      browser: 'Chrome 124 on macOS',
      os: 'macOS Sonoma',
      deviceType: 'desktop',
      requestId: 'req_audit_5510283b',
    },
    hashSignature: 'sha256:d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
    httpStatus: 200,
  },
];
